### ISSUE TITLE
use with Android?

### ISSUE THREAD

**Issue by venil7** [pengrad/java-telegram-bot-api#1]
I get the following message from build process
`"major version 52 is newer than 51, the highest major version supported by this compiler.
 [javac]   It is recommended that the compiler be upgraded." `

which suggests that library requires Java 8
is there no way to use it with Android?

**Comment by venil7** [comment]
should have RTFMed :+1:

**Comment by pengrad** [comment]
Thanks for issue.
Please use new version built with Java 6.
compile 'com.github.pengrad:java-telegram-bot-api:1.0.3'

**Comment by venil7** [comment]
@pengrad thanks
