### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by kiberzoid** [pengrad/java-telegram-bot-api#103]
Hi,
I see the following warning in the tomcat's logs:

org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application appears to have started a thread named [OkHttp ConnectionPool] but has failed to stop it. This is very likely to create a memory leak. 

Is this a library(OkHttp) problem?

**Comment by pengrad** [comment]
Really I don't know, probably they fixed it
https://github.com/square/okhttp/issues/1306
