### ISSUE TITLE
How I can set InlineKeyboardButton vertically?

### ISSUE THREAD

**Issue by jgarcia-controltechcg** [pengrad/java-telegram-bot-api#104]
Greetings to all.

I want to show the InlineKeyboardButtons vertically, but I do not find any method in the API to do it.
Does the library have any way to do it?

Thank you.

**Comment by pengrad** [comment]
Hi, this api just matches original Telegram Bot Api.
Show me how you can do this with Telegram's API, I will show you how to repeat with my
