### ISSUE TITLE
High CPU usage in UpdatesListener when network is down

### ISSUE THREAD

**Issue by dya-tel** [pengrad/java-telegram-bot-api#107]
When network is down (or OkHttp for any reason can't connect to Telegram server), UpdatesListener#onFailure is being executed. In this case request is repeated so the loop doesn't break and it's perfectly fine. The problem here is that the next request starts immediately, immediately fails and so on. Thus we get something like an infinite loop that uses A LOT of CPU, which is pretty bad.

Similar problem rises even when everything is fine as we get "infinite loop" for processing with, again, high CPU usage (though a lot smaller, as there is a delay due to request time), and more over, network usage. But I'm not too sure if this case requires fixing. In my opinion, 100-200ms request delay should be sufficient.

The solution is pretty simple: add "cooldown time" after each request. Probably, default "cooldown" after failures should be about few seconds.

**Comment by pengrad** [comment]
Agree, i think sleep for 100ms in onFailure will be enough

**Comment by dya-tel** [comment]
It probably should be configurable. For example, you can add an overloading method:
`TelegramBot#setUpdatesListener(Long, Long, UpdatesListener)`

**Comment by pengrad** [comment]
I don't like such a fine tuning in this method. 
It's more high level

**Comment by dya-tel** [comment]
Well, it should be configurable at least somewhere. Because some people will want no-delay requests, and some people will want as less CPU usage as possible.

> It's more high level
I don't see any problems here. The old `TelegramBot#setUpdatesListener(UpdatesListener)` stays as it was, but now it just passess default values to the new method. And the new method could be used by the user if he wants non-default values. Maybe, two different values is an overkill, but you get the idea.

**Comment by pengrad** [comment]
Yes, i will add it in TelegramBotAdapter. 
It's time to introduce Builder pattern there :)

**Comment by pengrad** [comment]
Fixed in 3.4.0
