### ISSUE TITLE
API 3.3: UpdatesListener.CONFIRMED_UPDATES_ALL loop on Sticker received

### ISSUE THREAD

**Issue by novic** [pengrad/java-telegram-bot-api#110]
Have a loop of update receiving when Sticker have been received on API 3.3.

bot.setUpdatesListener(new UpdatesListener() {
            @Override
            public int process(List<Update> updates) {
                // process updates
                for (Update update : updates) {
                    Message message = update.message();
...
                }
                return UpdatesListener.CONFIRMED_UPDATES_ALL;
            }
        });

**Comment by pengrad** [comment]
Can you reproduce it calling getUpdates directly with offset = sticker_update_id + 1?

**Comment by novic** [comment]
Calling getUpdates directly with offset = sticker_update_id + 1 - **is OK**:

GetUpdates getUpdates = new GetUpdates().limit(100).timeout(0);
        bot.execute(getUpdates.offset(updateId), new Callback<GetUpdates, GetUpdatesResponse>() {
            @Override
            public void onResponse(GetUpdates request, GetUpdatesResponse response) {
                List<Update> updates = response.updates();
                for (Update update : updates) {
                    Message message = update.message();
                    Log.d(LOG_TAG, "Message received with ID: " + message.messageId());
                    updateId = update.updateId() + 1;
                }
            }
            @Override
            public void onFailure(GetUpdates request, IOException e) {
            }
        });

**Comment by pengrad** [comment]
But listener actually do the same. 
You can create bot with `buildDebug` and check logs

**Comment by pengrad** [comment]
@novic is it still relevant?

**Comment by novic** [comment]
@pengrad The problem was solved for me in the 3.3.0 version. Thanks!
