### ISSUE TITLE
Top Message

### ISSUE THREAD

**Issue by DenisWpk** [pengrad/java-telegram-bot-api#114]
Hi, Stanislav!

How I can make this message, using you library?
![0c794d99-f175-48ee-9b56-7fe7ca59453a](https://user-images.githubusercontent.com/8546089/32892806-3e2c9ade-caf9-11e7-9f91-f882ae99ae62.jpg)

Thank you!

**Comment by BrainStone** [comment]
That should be pinning it.

**Comment by pengrad** [comment]
https://core.telegram.org/bots/api#pinchatmessage

**Comment by DenisWpk** [comment]
But its not pinned. This message show on two seconds and hide. 
If i use PinChatMessage method i catch error: Bad Request: method is available only for supergroups and channels.
My question about bot.

**Comment by BrainStone** [comment]
The error says it all. The group needs to be a supergroup (you can turn a group into a supergroup in the group settings)

**Comment by DenisWpk** [comment]
BrainStone, thank you for answer but I say about conversation bot with user. Its not group.
Message like this:
![screenshot_20171121-071138 2](https://user-images.githubusercontent.com/8546089/33051378-720dd09e-ce8b-11e7-9636-2904db4739b5.png)
