### ISSUE TITLE
Could you please set Long instead of Integer. For today's, the current update_id is 974825709

### ISSUE THREAD

**Issue by IvanYarovyi** [pengrad/java-telegram-bot-api#117]
https://github.com/pengrad/java-telegram-bot-api/blob/7a6af9dc86201016457c34c2f9f41156acdaf929/library/src/main/java/com/pengrad/telegrambot/model/Update.java#L12

**Comment by pengrad** [comment]
In telegram doc https://core.telegram.org/bots/api#available-types

> It is safe to use 32-bit signed integers for storing all Integer fields unless otherwise noted.

**Comment by IvanYarovyi** [comment]
Thank you for a prompt reply.
