### ISSUE TITLE
Unnecessary field in the editMessageCaption and editMessageReplyMarkup methods?

### ISSUE THREAD

**Issue by burs** [pengrad/java-telegram-bot-api#119]
Hi, 

I cannot find the field "text" in the methods [editMessageCaption](https://core.telegram.org/bots/api#editmessagecaption) and [editMessageReplyMarkup](https://core.telegram.org/bots/api#editmessagereplymarkup) from the official api. You have this field in constructors for both of these requests. Is this intentional?

Best regards,
burs

**Comment by isChanged** [comment]
I agree with the opinion of burs.
We need another constructor to remove the inline buttons only

**Comment by pengrad** [comment]
there was no special intention, i think it's just a copy-paste from EditMessageText :)

**Comment by pengrad** [comment]
Released in 3.5.2
