### ISSUE TITLE
Missing method in the addStickerToSet request

### ISSUE THREAD

**Issue by burs** [pengrad/java-telegram-bot-api#120]
Hi,

I think the optional field mask_position is missing in the [addStickerToSet](https://core.telegram.org/bots/api#addstickertoset) method.

Best regards,
burs

**Comment by pengrad** [comment]
@burs Thanks a lot again for finding such mistakes!
I'm ready to release 3.5.2 with these fixes, but maybe you will find couple more misses?

**Comment by burs** [comment]
Hi @pengrad,
Thanks for the reply. I'm now done looking at the Available Methods, Updating Messages, and Stickers methods in the api. Haven't found anything else so far. I'm not going to be able to continue until next week. Keep up the good work!
Best regards,
burs

**Comment by pengrad** [comment]
Released in 3.5.2
