### ISSUE TITLE
get chat members

### ISSUE THREAD

**Issue by ukt** [pengrad/java-telegram-bot-api#121]
in README.md presents information:

```
GetChatMembersCount

class GetChatMembersCountResponse  { 
  ChatMember chatMember() 
}
```
 But GetChatMembersCountResponse didn't has implementation of chatMember. Only count. Also GetChatMember has  chatMembe, but in README.md presents count;

I think need fix readme.md

**Comment by pengrad** [comment]
Hi, thank you!
Yes, need to fix readme, and you can send PR :)

**Comment by ukt** [comment]
Ok, maybe in next time
