### ISSUE TITLE
Create vertical InlineButton 

### ISSUE THREAD

**Issue by mrb4hr4m** [pengrad/java-telegram-bot-api#122]
Hi . i want to create vertical inline buttons like this 

[https://core.telegram.org/file/811140659/1/RRJyulbtLBY/ea6163411c7eb4f4dc](url)

`InlineKeyboardMarkup inlineKeyboard = new InlineKeyboardMarkup(
                new InlineKeyboardButton[]{
                        new InlineKeyboardButton("url").url("http://google.com"),
                        new InlineKeyboardButton("callback_data").callbackData("callback_data"),
                        new InlineKeyboardButton("switch_inline_query").switchInlineQuery("switch_inline_query")
                });`

The following code is worked but there is no way to change buttons orintation

**Comment by pengrad** [comment]
`InlineKeyboardMarkup` takes Array of Array of `InlineKeyboardButton`.
Every array is row.
In your case you need to create 3 arrays with 1 InlineKeyboardButton in each.

**Comment by mrb4hr4m** [comment]
Thank Thank Thank :)
