### ISSUE TITLE
SendAudio && SendVoice exception

### ISSUE THREAD

**Issue by novic** [pengrad/java-telegram-bot-api#127]
Exception with null message while using SendAudio or SendVoice:

try {
java.io.File recFile = new java.io.File("/path/to/file.wav");
SendAudio request = new SendAudio(chatId, recFile);
SendResponse sendResponse = bot.execute(request);
} catch (Exception e) {
}

Exception: e.getMessage(): null

**Comment by pengrad** [comment]
I don't know how to reproduce it, test for `sendAudio` works fine
And you didn't provide any stacktrace, i just don't know how to help you

**Comment by novic** [comment]
Stack trace is:

01-25 14:32:30.069 17856-17856/su.anikos.tgbot W/System.err: android.os.NetworkOnMainThreadException
01-25 14:32:30.069 17856-17856/su.anikos.tgbot W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:86)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:752)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.Dns$1.lookup(Dns.java:39)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:213)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-25 14:32:30.070 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at okhttp3.RealCall.execute(RealCall.java:77)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:56)
01-25 14:32:30.071 17856-17856/su.anikos.tgbot W/System.err:     at com.pengrad.telegrambot.TelegramBot.execute(TelegramBot.java:36)

**Comment by novic** [comment]
SendMessage is almost OK there.

**Comment by pengrad** [comment]
So your error is `android.os.NetworkOnMainThreadException`.
Use `AsyncTask` or `execute with callback`

**Comment by novic** [comment]
Thanks a lot!!! Callback method works great!
