### ISSUE TITLE
Use of SendVideo to send a YouTube video.

### ISSUE THREAD

**Issue by jorgealfonsogarcia** [pengrad/java-telegram-bot-api#128]
Greetings!

I'm trying to send a YouTube video using the class SendVideo but I do not receive any type of response from the library or from the API and neither does the message reach the recipient.

This is the instruction I have for sending the URL of the video:

`telegramBot.execute(new SendVideo(update.callbackQuery().from().id(), "https://www.youtube.com/watch?v=C0DPdy98e4c"));`

Thank you for your attention and help.

**Comment by pengrad** [comment]
Build your bot with debug mode to check all logs.
`{"ok":false,"error_code":400,"description":"Bad Request: wrong type of the web page content"}`
I think it's because Telegram can't parse video on youtube now
