### ISSUE TITLE
BotUtils.parseUpdate dosn't work properly when the update comes from a "InlineKeyboardButton"

### ISSUE THREAD

**Issue by IgnacioArellano** [pengrad/java-telegram-bot-api#134]
[update from InlineKeyboardButton.txt](https://github.com/pengrad/java-telegram-bot-api/files/1862747/update.from.InlineKeyboardButton.txt)

**Comment by pengrad** [comment]
Why don't you spend couple minutes to tell what is wrong?
Everything is fine for me

**Comment by IgnacioArellano** [comment]
I'm using a webhook and BotUtils.parseUpdate to parse the incoming JSON.

`update = BotUtils.parseUpdate(in_json);`

All work fine for text messages and images. Now I'm tring to use an Inline Keyboard in my bot.
![16bac464-a612-4315-a50e-d7aca80569ac](https://user-images.githubusercontent.com/30451416/38176947-e49f292a-35bd-11e8-89a1-cf749de4d22a.jpg)
The problem is, when run the callbackQuery() metod of "Update" class that sems to return null.

`CallbackQuery cbq = update.callbackQuery();`

I use the following code to check:

`if(cbq == null){`
`  SendMessage request = new SendMessage(userID,"Call back query is empty!!");`
  `SendResponse sendResponse = bot.execute(request);`  
`}else{`    
  `SendMessage request = new SendMessage(userID,cbq.data());`
  `SendResponse sendResponse = bot.execute(request);`
`}`

![e5b963c9-90b6-4750-9de9-0f8fde876789](https://user-images.githubusercontent.com/30451416/38176929-9e56ff9c-35bd-11e8-8f7e-dcb46b57d616.jpg)


May be I'm not handling CallbackQuery the right way, thanks a lot for your help !! :)
