### ISSUE TITLE
Cant insert a line break ("\n", "%0A", ...)

### ISSUE THREAD

**Issue by CustomCraftDev** [pengrad/java-telegram-bot-api#14]
http://prntscr.com/ad0olp

**Comment by pengrad** [comment]
When you want new line you need "\n" not "\\n", and it works.
What about "%0A" – it's just a string for Java, you should decode it by yourself.

**Comment by CustomCraftDev** [comment]
thanks for your quick answer, but it does not work.
a short working example would be nice.

ps: i know that %0A is just a string ... but url-encoding / escaping it also does not work ...

**Comment by pengrad** [comment]
try `sendMessage("Test \n test");` it should work.

**Comment by CustomCraftDev** [comment]
it did not at first ^^ ... but i got it working ...
the string was automatically escaped to \\n ... i just had to decode it again.

thanks for the help.
case closed ...
