### ISSUE TITLE
Probable error

### ISSUE THREAD

**Issue by clgx-ivan** [pengrad/java-telegram-bot-api#141]
https://github.com/pengrad/java-telegram-bot-api/blob/08bb06515e6ef222ff93d77b6e1e0eb3dd5eaafe/library/src/main/java/com/pengrad/telegrambot/impl/UpdatesHandler.java#L42
Hi,
could this method lead to StackOverflowError?

**Comment by pengrad** [comment]
It doesn’t call itself direclty. It happens async from callback
