### ISSUE TITLE
 Bad Request: message can't be edited

### ISSUE THREAD

**Issue by robatipoor** [pengrad/java-telegram-bot-api#149]
```
Long chatId = update.message().chat().id();
int messageId = update.message().messageId();
EditMessageCaption editMessageCaption = new EditMessageCaption(chatId, messageId).caption("edited ...");
BaseResponse res = bot.execute(editMessageCaption);
System.err.println(res.description());
```
i can't edit caption message anybody tell me why get bad request  ?

**Comment by pengrad** [comment]
I think response is quite clear. You are trying to edit not own message.
From telegram api doc:
`Use this method to edit captions of messages sent by the bot or via the bot (for inline bots).`

**Comment by robatipoor** [comment]
thank you for your response
