### ISSUE TITLE
Channel Bot Example

### ISSUE THREAD

**Issue by Unixcision** [pengrad/java-telegram-bot-api#15]
Hi!
Can u post a bot code example that sends messages to a channel? I don't know how to start coding using your api, I'm so confused.
Thanks!

**Comment by pengrad** [comment]
Hi, its very easy!
Everything is in README.
Assume that you already have a token:
```java
// create bot
TelegramBot bot = TelegramBotAdapter.build("BOT_TOKEN"); 

// send message simple syntax
bot.sendMessage("@mychannel", "short message sending");

// send message full syntax
bot.sendMessage(
    chatId,                    // chat_id
    "Hello _italic_ *bold*!",  // text
    ParseMode.Markdown,        // Markdown text or null
    false,                     // disable_web_page_preview
    replyMessageId,            // reply_to_message_id
    new ReplyKeyboardMarkup(new String[]{"ok", "cancel"}).oneTimeKeyboard(true));  // keyboard
```

**Comment by Unixcision** [comment]
Thanks! But I do not know how to compile the project to .jar, can u explain me the steps from downloading the source to executing the compiled code? I will thank you a lot.
PD: I use a Linux server to compile and run the not.

**Comment by pengrad** [comment]
Use gradle or maven

**Comment by Unixcision** [comment]
Can I ask u another thing?

**Comment by Unixcision** [comment]
I forgot to reply you, but I do not know how to compile in cradle/maven and where to put the bot code and the API code, I'm confused because I didnt use it yet.
Thanks!
