### ISSUE TITLE
How to send bold/italic/monospaced?

### ISSUE THREAD

**Issue by j1mmyx** [pengrad/java-telegram-bot-api#153]
as I know, simply text format work with telegram is:

Bold : **text**
Italic : __text__
Monospace Font : `text`

it's working when I'm try that method direcly on telegram.
but in BOT, it will print character, not changing text format.

please help.. i need to format number with monospace font for easy-read digits
sorry for my bad English. Thanx

**Comment by pengrad** [comment]
Use `Markdown` or `HTML` formatting option
https://core.telegram.org/bots/api#formatting-options

```java
SendMessage sendMessage = new SendMessage(chatId, "*bold* _italic_ `inline`")
                .parseMode(ParseMode.Markdown);
SendResponse sendResponse = bot.execute(sendMessage);
```

**Comment by j1mmyx** [comment]
Thank you so much!!
