### ISSUE TITLE
Exceptions cause update loop

### ISSUE THREAD

**Issue by itsTyrion** [pengrad/java-telegram-bot-api#161]
Code that throws an exception in the update listener, in my case 
`msg.newChatMembers().length` without checking makes the api jump into the `onFailure` block without throwing an exception or printing a stack trace, leading to an infinite update loop. 

How to reproduce? 
`update.message().newChatMembers().length` without a null check on `newChatMembers()` and send a text or voice message

**Comment by pengrad** [comment]
Ideas how it can be properly handled?
Additional ErrorListener as a 2nd lambda param?
Still not sure how to skip or mark this update as processed.

**Comment by itsTyrion** [comment]
maybe. or print the stacktrace. or make the 2nd parameter optional and just print it by default^^

**Comment by pengrad** [comment]
New behavior:
1. Exception in UpdateListener will fail and stop update handler
2. Network failure or exception in library will be logged and updates continue
3. Bad response from API will be logged and updates continue

Will release with next major version, but you can always try master snapshot with jitpack
https://jitpack.io/#pengrad/java-telegram-bot-api/master-SNAPSHOT
