### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by ARM4T00R4** [pengrad/java-telegram-bot-api#166]
Hi. In your 'Usage' I have a error on this line
`long chatId = update.message().chat().id();`

I have this:
`Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	update cannot be resolved`

**Comment by pengrad** [comment]
Well, it’s compile error, you need to receive that `update` object first.
Calling `getUpdates` or using update listener

**Comment by pengrad** [comment]
Agree, maybe example is confusing.
Try this one
```java
bot.setUpdatesListener(updates -> {
    for (Update update : updates) {
        // there could be different updates (InlineQuery, Poll...)
        if (update.message() != null) {
            long chatId = update.message().chat().id();
            SendResponse response = bot.execute(new SendMessage(chatId, "Hello!"));
        }
    }
    return UpdatesListener.CONFIRMED_UPDATES_ALL;
});
```

**Comment by ARM4T00R4** [comment]
Thanks! Your new code is working! Please, change your 'Usage' for other newbies.
