### ISSUE TITLE
text mention and forward from

### ISSUE THREAD

**Issue by salahcode** [pengrad/java-telegram-bot-api#175]
forward_from &&
mention
is always null in messages? why

please update animated sticker

**Comment by salahcode** [comment]
forward_from &&
                      text mention 
                                         is always null in messages? why

**Comment by salahcode** [comment]
forward_from &&
text mention
is always null in messages? why

**Comment by pengrad** [comment]
Would be great to see more details :)
What request? What response? How is it related with animated sticker?

**Comment by salahcode** [comment]
i make the robot to manage whole the supergroup
i have some issues
1.when someone forward from chat forward_from is null but forward_sender_name not null
2.when someone send username (@username) to group MessageEntity not null but MessageEntity.user is null
3. i need to find userid by username for supergroup and seprate
4.when i send animated sticker to the group is not show to (log) but message id is updated

**Comment by salahcode** [comment]
![photo_2019-07-27_12-44-42](https://user-images.githubusercontent.com/16436824/61991972-3a723d80-b06d-11e9-804e-8b3eabcd5273.jpg)
![photo_2019-07-27_12-44-47](https://user-images.githubusercontent.com/16436824/61991973-3b0ad400-b06d-11e9-83e4-403fa41cac82.jpg)
can you edited this request

**Comment by salahcode** [comment]
when send message forward form private ,forward_from is null but name_sender not null
when send message forward from supergroup name_sender null but forward_from not null

**Comment by pengrad** [comment]
That's correct, you have `forward_from` or `forward_sender_name` if user wants to hide account. (Sender's name for messages forwarded from users who disallow adding a link to their account in forwarded messages) 

https://core.telegram.org/bots/api#message

**Comment by salahcode** [comment]
thanks I understood :D but why mention user , user is null in MessageEntity 
how GetChatMember by username find userid
how see message with animated sticker 
in new update telegram RestrictChatMember and PromoteChatMember is changed to Permissions 
when update this library

**Comment by pengrad** [comment]
1. user in MessageEntity works only for users without usernames
https://telegram.org/blog/edit#new-mentions

2. I don't know, find this on Telegram API doc and this method will be in this library.

3. Messages with animated stickers are there, don't see problems with them. The only difference is Telegram set `"is_animated":true` which is missed in this library, but this field is not official released yet. Need more info

4. Don't understand, I see both RestrictChatMember and PromoteChatMember methods work fine, and don't see any permissions update on Bot API

**Comment by salahcode** [comment]
thanks a lot , sorry for my little English :))) i understood but let me explain this 
4.i tested both RestrictChatMember and PromoteChatMember methods but not work fine i think because Api's changed not work fine If you see the photo you will notice and i need more ability for RestrictChatMember like send poll ,add user,pin message and change chat info 
 
![Screenshot_2019-07-29_13-26-34](https://user-images.githubusercontent.com/16436824/62037902-f0728e80-b209-11e9-9ad3-55ab4601c290.png)
![photo_2019-07-29_14-00-34](https://user-images.githubusercontent.com/16436824/62037935-01bb9b00-b20a-11e9-97e0-e38cc409a78f.jpg)
![Screenshot_2019-07-29_13-32-15](https://user-images.githubusercontent.com/16436824/62037949-06804f00-b20a-11e9-9072-866ec7572237.png)
![photo_2019-07-29_14-00-38](https://user-images.githubusercontent.com/16436824/62037969-10a24d80-b20a-11e9-8f3d-18e3764a4aae.jpg)
sorry about that I took your time :(

**Comment by pengrad** [comment]
well, it seems not yet available from API
https://core.telegram.org/bots/api#restrictchatmember

when it will - i will immediately add to the library

**Comment by salahcode** [comment]
thanks a lot
