### ISSUE TITLE
mention 

### ISSUE THREAD

**Issue by salahcode** [pengrad/java-telegram-bot-api#178]
i problem with mention 
i can username mention in text message with parseMod.HTML
(<a href==\"https://t.me/$username\">$name</a>)
but i can't mention user without username how can i fix it

in php {
<a href==mention:@danogentili>Mention by username</a>
<a href==mention:186785362>Mention by user id</a>
}

thank your for answer
and update is awesome <3

**Comment by pengrad** [comment]
Thank you!

I don't know how bot can mention user without username. 
In my tests MessageEntity.user is available only when user send this mentioning to bot.

I suggest you to ask on Stackoverflow.

**Comment by salahcode** [comment]
i found this :)
  val msg = "[username](tg://user?id=706514791)"
  bot?.execute(SendMessage(chatId,msg).parseMode(ParseMode.Markdown))

work very well 
thanks
