### ISSUE TITLE
find user_id

### ISSUE THREAD

**Issue by salahcode** [pengrad/java-telegram-bot-api#179]
i can find user by GetChat(userid) and GetChatMember(chatid,userid)
but i want to find userid by username ..username is unique but maybe is not exist 
 is it possible may be a way i find userid by username or GetChat and GetChatMember method can find userid by username 

to other language (php) GetChat and GetChatMember work by username how can i do it

**Comment by pengrad** [comment]
Both GetChat and GetChatMember takes chatId param as 
```
Unique identifier for the target chat or username of the target supergroup or channel (in the format @channelusername)
```
username can be specified for channels only. 
I've tested, it works for channels, and not for private chats.

Please provide HTTP request that works for user's username

**Comment by salahcode** [comment]
thanks
I realized that I had to work from the client side to get the user
