### ISSUE TITLE
Please help me see what is causing the Connection reset!

### ISSUE THREAD

**Issue by biuaxia** [pengrad/java-telegram-bot-api#180]
Hello, I am a developer from China.
When I use your github code, the connection timed out always appears, but it is normal for me to access tg myself. Is there any way to solve it?

Here is the code when i reproduce the error:

```java
        OkHttpClient client = new OkHttpClient.Builder()
                .addInterceptor(chain -> {
                    Request request = chain.request()
                            .newBuilder()
                            .addHeader("Accept-Encoding", "gzip, deflate")
                            .addHeader("Connection", "keep-alive")
                            .addHeader("Accept", "*/*")
                            .build();
                    return chain.proceed(request);
                })
                .build();

        TelegramBot bot = new TelegramBot.Builder("Token").okHttpClient(client).build();
        GetMe request = new GetMe();
        GetMeResponse execute = bot.execute(request);

        System.out.println(execute.toString());
        User user = execute.user();
        System.out.println(user);
```

**Comment by biuaxia** [comment]
> Hello, I am a developer from China.
> When I use your github code, the connection timed out always appears, but it is normal for me to access tg myself. Is there any way to solve it?
> 
> Here is the code when i reproduce the error:
> 
> ```java
>         OkHttpClient client = new OkHttpClient.Builder()
>                 .addInterceptor(chain -> {
>                     Request request = chain.request()
>                             .newBuilder()
>                             .addHeader("Accept-Encoding", "gzip, deflate")
>                             .addHeader("Connection", "keep-alive")
>                             .addHeader("Accept", "*/*")
>                             .build();
>                     return chain.proceed(request);
>                 })
>                 .build();
> 
>         TelegramBot bot = new TelegramBot.Builder("Token").okHttpClient(client).build();
>         GetMe request = new GetMe();
>         GetMeResponse execute = bot.execute(request);
> 
>         System.out.println(execute.toString());
>         User user = execute.user();
>         System.out.println(user);
> ```

**Comment by pengrad** [comment]
Hi, try to set timeouts on OkHttpClient builder
```
new OkHttpClient.Builder()
    .connectTimeout(75, TimeUnit.SECONDS)
    .readTimeout(75, TimeUnit.SECONDS);
```
