### ISSUE TITLE
How to check if the connection was established successfully

### ISSUE THREAD

**Issue by ZzetT** [pengrad/java-telegram-bot-api#186]
Hi,

with the update callbacks the user gets notified for a response or a failure.

But is there any possibility to get notified or to check if the connection to the Telegram server was established successfully? If there is no message from a user, I also don't get a notification. So I don't know at what point in time I can be sure that we are waiting for updates. The only way I can think of is to wait for a certain amount of time and if no failures were received, then it it is very likely that everything went well. Or is there any better way to do that?

**Comment by pengrad** [comment]
Hi, there is no way to do this on `UpdateListener` level - it's more like a local "webhook" to just get notified about incoming updates.

Possible workarounds for you:

1) You can run your updates manually but calling `bot.execute(new GetUpdates())`.
This won't tell you if connection is established but you can assume that once you have called `execute` you are waiting for updates.

2) You can use `EventListener` for OkHttp client (network library used in this library) and build your bot with custom OkHttpClient instance. This will allow you to get all connection details. https://square.github.io/okhttp/events/
