### ISSUE TITLE
it did not compiled on android studio 1.5.1

### ISSUE THREAD

**Issue by gkamaall** [pengrad/java-telegram-bot-api#19]
i add the github (compile 'com.github.pengrad:java-telegram-bot-api:1.3.2') in dependencies.
but gradel have errror :-1: 
 Error:(26, 13) Failed to resolve: com.github.pengrad:java-telegram-bot-api:1.3.2
<a href="openFile:E:/bottest/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by pengrad** [comment]
Problem on your side, i think. 
Post all yours build.gradle files.  понедельник, 18 апреля 2016г., 15:43 +07:00 от kamaall < notifications@github.com> :

**Comment by gkamaall** [comment]
this is build.gradle(module):

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.ipandroid.bottest"
        minSdkVersion 11
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.github.pengrad:java-telegram-bot-api:1.3.2'
}

**Comment by pengrad** [comment]
Try to add mavenCentral() to repositories in your root build.gradle
And turn off offline mode if its on.  понедельник, 18 апреля 2016г., 15:53 +07:00 от kamaall < notifications@github.com> :

>this is build.gradle(module):
>apply plugin: 'com.android.application'
>android {
>compileSdkVersion 23
>buildToolsVersion "23.0.2"
>defaultConfig {
    applicationId "com.ipandroid.bottest"
    minSdkVersion 11
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}

**Comment by gkamaall** [comment]
it not work!
i try in 3 day.
plz send *.jar file

**Comment by pengrad** [comment]
Exec in terminal in the root of project:
./gradlew 
Any errors? понедельник, 18 апреля 2016г., 16:11 +07:00 от kamaall < notifications@github.com> :

**Comment by gkamaall** [comment]
plz send me jar file to my email gkamaall@gmail.com
i will try after update android studio to 2 and jdk to 8

**Comment by pengrad** [comment]
I tried to build it for android. Everything is ok. 
Sorry, I wont build jar for you. 
Try to understand why you cant resolve dependencies.

**Comment by pengrad** [comment]
Take it from here
https://oss.sonatype.org/content/repositories/releases/com/github/pengrad/java-telegram-bot-api/1.3.3/
