### ISSUE TITLE
How to use Poll API 2.0

### ISSUE THREAD

**Issue by SpecialAgentX** [pengrad/java-telegram-bot-api#193]
Hi Pengrad,

thank you for this API. Im having problems to send a Poll to my chat. Actually I do not understand the API here.
Could you please provide some examples how to use Poll, PollOption and PollAnswer classes?

Thank you!

**Comment by pengrad** [comment]
Hi, while I'm preparing a proper example you can take a look on tests for poll methods.
https://github.com/pengrad/java-telegram-bot-api/blob/master/library/src/test/java/com/pengrad/telegrambot/TelegramBotTest.java#L1445

**Comment by pengrad** [comment]
You send polls like this:
```
String question = "Question ?";
String[] answers = {"Answer 1", "Answer 2"};
SendResponse sendResponse = bot.execute(
        new SendPoll(groupId, question, answers)
                .isAnonymous(false)
                .type(Poll.Type.quiz)
                .allowsMultipleAnswers(false)
                .correctOptionId(1)
                .isClosed(true)
);
Poll poll = sendResponse.message().poll();
```

And receive answers from `Update` which you get vie Webhooks, getUpdates or [UpdatesListener](https://github.com/pengrad/java-telegram-bot-api#updates-listener)
```
Update update = webhook_or_getUpdates();

PollAnswer pollAnswer = update.pollAnswer();
String id = pollAnswer.pollId();
Integer[] options = pollAnswer.optionIds();
User user = pollAnswer.user();
```
