### ISSUE TITLE
SendDocument change file type pdf to always .txt

### ISSUE THREAD

**Issue by maxim-grinchenko** [pengrad/java-telegram-bot-api#197]
use SendDocument for send .pdf

     // file:application/pdf;base64,JVBERi0xLjMN...DAwMT==
      private String sendFileToClient(String clientExtId, String file) {
        String fileLink;
        byte[] data = DatatypeConverter.parseBase64Binary(file);
        SendDocument sendDocument = new SendDocument(clientExtId, data);
        try {
            SendResponse execute = telegramBot.execute(sendDocument);
            Document document = execute.message().document();
            final String documentId = document.fileId();
            fileLink = getFileLink(documentId); ///file_203.txt
            return fileLink;
        } catch (Exception e) {
            ....
        }
    }

run code and always get type .txt (not pdf)
provided for change content-type to pdf? 
how to get the .pdf?

**Comment by pengrad** [comment]
You need explicitly specify file name by:
`new SendDocument(clientExtId, data).fileName("doc.pdf")`

Name in the link will be ignored but extension will be correct
