### ISSUE TITLE
could not send any message with '<' character

### ISSUE THREAD

**Issue by spidol-pulpen** [pengrad/java-telegram-bot-api#198]
I cannot send any message with '<' character in it. However, '>' is working. Sending only '<' is also not working. I use version 4.7.0, with the following code:

```
SendMessage msg = new SendMessage(chatId, message);
msg.parseMode(ParseMode.HTML);

bot.execute(msg);
```

**Comment by pengrad** [comment]
Yes, that's correct you are sending HTML so you need to escape this symbol or it is treated as a starting html tag.

There is an error from Telegram API 
`"error_code":400,"description":"Bad Request: can't parse entities: Unsupported start tag \"\" at byte offset N"}`

I found that `<` is the only symbol they do not parse, `" > &` work fine.
So you probably only need to replace `<` to `&lt;`

Something like this on your text content should be fine:
```
content.replaceAll("<", "&lt;");
```

But be careful to not escape whole HTML message, as you don't want to lose you tags.

**Comment by spidol-pulpen** [comment]
Ok. Sorry, you're right. Thank you very much for your support.
