### ISSUE TITLE
Sending special characters

### ISSUE THREAD

**Issue by torbeneims** [pengrad/java-telegram-bot-api#199]
I would like to send a String containing special characters `"ä ö ü ß 😀"`

Before doing anything complex, I tried

    TelegramBot bot = new TelegramBot(System.getenv("TELEGRAM_BOT_TOKEN"));
    SendResponse response = bot.execute(new SendMessage(1076643869, "ä ö ü ß 😀"));
    System.out.println(response.message().text());

from which I receive a message containing `Ã¤ Ã¶ Ã¼ ÃŸ ðŸ˜€` and `ä ö ü ß 😀` in the console.

I suspect that there is no fundamental error in my charset, since sending a HTTP POST request manually does not produce the error:

    OutputStreamWriter writer = null;
    BufferedReader reader = null;
    try {
    	URL url = new URL("https://api.telegram.org/bot" + System.getenv("TELEGRAM_BOT_TOKEN") + "/sendMessage");
    	String payload = "{\"chat_id\": 1076643869, \"text\": \"ä ö ü ß 😀\"}";
    	
    	HttpURLConnection con = (HttpURLConnection) url.openConnection();
    	con.setRequestMethod("POST");
    	con.setDoInput(true);
    	con.setDoOutput(true);
    	con.setUseCaches(false);
    	con.setRequestProperty("Content-Type", "application/json");
    	con.setRequestProperty("Content-Length", String.valueOf(payload.length()));
    	
    	writer = new OutputStreamWriter(con.getOutputStream());
    	writer.write(payload);
    	writer.flush();
    	
    	reader = new BufferedReader(new InputStreamReader(con.getInputStream()));
    	
    	StringBuilder builder = new StringBuilder();
    	for (String line; (line = reader.readLine()) != null; ) {
    		builder.append(line);
    	}
    	
    } catch (IOException e) {
    	e.printStackTrace();
    } finally {
    	try {
    		if (writer != null)
    			writer.close();
    		if(reader != null)
    			reader.close();
    	}  catch (IOException e) {
    		System.err.format("Cant close writer or reader: %s%n", e);
    	}
    }

sending a message containing `ä ö ü ß 😀`

Thanks to pengrad's quick reply to my email, I could figure out that I am using the default windows charset;

    System.out.println(System.getProperty("file.encoding")); // Prints windows-1252
    System.out.println(Charset.defaultCharset().name()); // Prints windows-1252

A stated above, I don't think that changing the charset via the VM options would fix the issue, although pengrad stated that it works fine for him (at least using "ä, ö, ü and ß")

**Comment by pengrad** [comment]
Try to build bot in debug mode and check raw request and response.
In my case it's: `text=%C3%A4%2C%20%C3%B6%2C%20%C3%BC%20and%20%C3%9F`

Debug bot: `TelegramBot bot = new TelegramBot.Builder("TOKEN").debug().build();`

**Comment by torbeneims** [comment]
request:

    text=%C3%83%C2%A4%20%C3%83%C2%B6%20%C3%83%C2%BC%20%C3%83%C5%B8%20%C3%B0%C5%B8%CB%9C%E2%82%AC

Hope I got it right 😅
response:
"text":"\u00c3\u00a4 \u00c3\u00b6 \u00c3\u00bc \u00c3\u0178 \u00f0\u0178\u02dc\u20ac"

**Comment by torbeneims** [comment]
Ok, now using "ä, ö, ü and ß"

    text=%C3%83%C2%A4%2C%20%C3%83%C2%B6%2C%20%C3%83%C2%BC%20and%20%C3%83%C5%B8
"text":"\u00c3\u00a4, \u00c3\u00b6, \u00c3\u00bc and \u00c3\u0178"

**Comment by pengrad** [comment]
Probably it's not charset if it does work with HttpURLConnection.
There are already incorrect symbols in request `text=%C3%83%C2%A4%20%C3%83%C2%B6%20%C3%83%C2%BC%20%C3%83%C5%B8%20%C3%B0%C5%B8%CB%9C%E2%82%AC`, can decode with any online url decoder.

This library uses OkHttp client to make requests, I really doubt there can be a problem, but let's verify. 
So we are building form body, can you check that this code works correct for you?
```java
FormBody.Builder builder = new FormBody.Builder(Charset.forName("UTF-8"));
builder.add("text", "ä, ö, ü and ß");
FormBody formBody = builder.build();
System.out.println(formBody.encodedValue(0));
System.out.println(formBody.value(0));
```
Should print:
```
%C3%A4%2C%20%C3%B6%2C%20%C3%BC%20and%20%C3%9F
ä, ö, ü and ß
```

If it's not could you explicitly specify new version of OkHttp in your gradle.build (or maven):
```
implementation "com.squareup.okhttp3:okhttp:4.5.0"
implementation 'com.squareup.okhttp3:logging-interceptor:4.5.0'
```
And try again.

**Comment by torbeneims** [comment]
I get

    %C3%83%C2%A4%2C%20%C3%83%C2%B6%2C%20%C3%83%C2%BC%20and%20%C3%83%C5%B8
    ä, ö, ü and ß

wether I specify the PkHttp version or not. So it looks like the problem lies in the encoding.

**Comment by pengrad** [comment]
Hey @torbeneims, did you solve it?

**Comment by torbeneims** [comment]
Unfortunately, I did not. To be honest, I have no clue what to do other than manually overwriting, thus changing the library used to execute the request...

**Comment by JVMBuilder** [comment]
Please add encoding UTF-8
