### ISSUE TITLE
Add getFile method

### ISSUE THREAD

**Issue by maratkalibek** [pengrad/java-telegram-bot-api#2]
https://core.telegram.org/bots/api#getfile

**Comment by pengrad** [comment]
Thanks!
Added in 1.1.0 version: 
compile 'com.github.pengrad:java-telegram-bot-api:1.1.0'

telegramBot.getFile(String fileId)
telegramBot.getFullFilePath(File file)
or just
telegramBot.getFullFilePath(String fileId)
