### ISSUE TITLE
Get original image

### ISSUE THREAD

**Issue by maxim-grinchenko** [pengrad/java-telegram-bot-api#200]
Hi!

1. user "send as a photo" to telegram bot, image, size example = 400*600px

2. I used

          public String getFileLink(String fileId) {
          GetFile getFile = new GetFile(fileId);
          GetFileResponse fileResponse = telegramBot.execute(getFile);
          File file = fileResponse.file();
          return telegramBot.getFullFilePath(file);
          }
	
3. return link on image size 212 x 320 (resize)

how get original image?
let's say the user does not know how "send as a file" ))

Thanks in advance for Your reply

**Comment by pengrad** [comment]
Hi! 
When user send you a photo there is an array of `PhotoSize` object in a message.
You probably take 1st element currently. 
And this array has photo in different sizes, there are `width`, `height` and `fileSize` attributes in `PhotoSize`. 

So you can take "desired" photo size from there, it will be different file id. 
For example take the biggest one by comparing width:

```
Update update = response.updates().get(0);
PhotoSize[] photoSizes = update.message().photo();
PhotoSize biggestPhoto = photoSizes[0];
for (PhotoSize photo : photoSizes) {
    if (photo.width() > biggestPhoto.width()) {
        biggestPhoto = photo;
    }
}
String fileId = biggestPhoto.fileId();
```

And then pass this `fileId` to your getFileLink method

**Comment by maxim-grinchenko** [comment]
thank you so much for your help, you're right

**Comment by zeahouse** [comment]
> Hi!
> 
> 1. user "send as a photo" to telegram bot, image, size example = 400*600px
> 2. I used
>    ```
>       public String getFileLink(String fileId) {
>       GetFile getFile = new GetFile(fileId);
>       GetFileResponse fileResponse = telegramBot.execute(getFile);
>       File file = fileResponse.file();
>       return telegramBot.getFullFilePath(file);
>       }
>    ```
> 3. return link on image size 212 x 320 (resize)
> 
> how get original image? let's say the user does not know how "send as a file" ))
> 
> Thanks in advance for Your reply

I have the same problem. I has saved photo()[0] fileId, but when i try to download, i have a low resolution.
