### ISSUE TITLE
Cannot build or run release with OpenJDK

### ISSUE THREAD

**Issue by lotusexpeditor** [pengrad/java-telegram-bot-api#206]
I can't run any release (java.lang.NoClassDefFoundError) with OpenJDK.

Linux 4.15.0-106-generic #107~16.04.1-Ubuntu SMP Thu Jun 4 15:40:05 UTC 2020 x86_64 GNU/Linux

openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~16.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

javac 1.8.0_252

 Also when I try to build I get following;

https://gist.github.com/lotusexpeditor/3d798062f9daf080bbebb622f0f7f7fb

**Comment by pengrad** [comment]
Try `./gradlew assemble` to build, you can’t run tests locally.
But NoClassDefFoundError looks like problem with your classpath.

**Comment by lotusexpeditor** [comment]
When I try to compile this code[1] with [2] or my build of the library I get following message

Build Command: javac -cp gson-2.8.6.jar:library.jar testBot.java

> Error: A JNI error has occurred, please check your installation and try again
> Exception in thread "main" java.lang.NoClassDefFoundError: com/pengrad/telegrambot/request/BaseRequest
> 	at java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
> 	at java.lang.Class.getMethod0(Class.java:3018)
> 	at java.lang.Class.getMethod(Class.java:1784)
> 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
> 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
> Caused by: java.lang.ClassNotFoundException: com.pengrad.telegrambot.request.BaseRequest
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 7 more

[1] https://gist.github.com/lotusexpeditor/36e6489715e71ae3ff1541a4ed3918f6
[2] https://github.com/pengrad/java-telegram-bot-api/releases/download/4.9.0/java-telegram-bot-api-full.jar

**Comment by lotusexpeditor** [comment]
My bad;

Run Command: java testBot

I didn't declared classpath in run command. Thank you!
