### ISSUE TITLE
Localize Readme

### ISSUE THREAD

**Issue by pengrad** [pengrad/java-telegram-bot-api#213]
add Russian, Chinese translations

**Comment by ny83427** [comment]
@pengrad I've been using your awesome library for a while and it's pretty straightforward. As a Chinese guy, just my opinion, Chinese translation is really not needed, as most of the stuff in README are codes with very simple instructions to follow.

However, if you really want Chinese translations, maybe I can help you translating the README to Chinese.

**Comment by pengrad** [comment]
Hi @ny83427, thank you!
I really think it will be very useful, so please help with translation.
You can send a PR with README_CN.md and we will link it on top of the original readme

**Comment by ny83427** [comment]
Sure, will do the translation job.

**Comment by CrazyBoyFeng** [comment]
I am Chinese, I think translation is not needed.   
If someone wants to use this library then they must understand the official telegram API. So developers must understand simple English.

**Comment by Fr0z3Nn** [comment]
> add Russian, Chinese translations

i can help you with russian translation🤔
