### ISSUE TITLE
Error in readme: "updatesResponse" should be "response"

### ISSUE THREAD

**Issue by msin87** [pengrad/java-telegram-bot-api#217]
https://github.com/pengrad/java-telegram-bot-api#get-updates
`public void onResponse(GetUpdates request, GetUpdatesResponse response)
 {List<Update> updates = updatesResponse.updates();}`
rename `updatesResponse.updates()` to `response.updates()`

**Comment by pengrad** [comment]
thanks!
why not Pull Request? 😀

**Comment by msin87** [comment]
> 
> 
> thanks!
> why not Pull Request? 😀

Oh, sorry. Next time =))
