### ISSUE TITLE
Kick the bot from a group

### ISSUE THREAD

**Issue by nautilor** [pengrad/java-telegram-bot-api#218]
I was wondering if there's a way to kick the bot from a group when added

I implemented my custom check to verify that a chat (group/channel) is allowed to have the bot in it and if the verification fails I would like the bot to kick itself from the chat

I found this

```java
bot.execute(new KickChatMember(chatId, userId));
```

but i don't think that this will help me at all or am I wrong?

**Comment by pengrad** [comment]
No, bot can not kick himself
You can add other bot which will be responsible for kicking only :)

**Comment by nautilor** [comment]
> No, bot can not kick itself
> You can add other bot which will be responsible for kicking only :)

there's a telegram API call as far as I know called `https://api.telegram.org/bot/leaveChat`
where you can specify the information to leave a chat

you can find more at https://core.telegram.org/bots/api#leavechat

**Comment by nautilor** [comment]
Oh my bad, I did not find it at first

```java
bot.execute(new LeaveChat(chatId))
```
works perfectly

**Comment by pengrad** [comment]
you also can just disallow users to add your bots to group. 
via BotFather -> Bot Settings -> Allow Groups
not sure will it disable channels though

**Comment by nautilor** [comment]
Yes but I am doing a filter on allowed chat manually to see if the bot should be in a group and the LeaveChat works perfectly
