### ISSUE TITLE
Java EE

### ISSUE THREAD

**Issue by antonanton** [pengrad/java-telegram-bot-api#22]
Hi. I am curious is this api working fine with Java EE? I am asking it because another java bot API listed in official telegram page have some troubles with concurrency in java EE.

Thanks.

**Comment by pengrad** [comment]
Hi, I know some problems with Google App Engine, but not with Java EE.
It's very easy to test, so you could try and tell me if something wrong.

**Comment by antonanton** [comment]
Definitely I will:) Thank you

**Comment by roabol** [comment]
Hello, I'm trying to run the api in a JEE application, using payara server. But when I run the simple routine of sending a message to a group I get an exception. I have already tried to enter the telegram certificate in the keystore.jks and cacert.jks of the $ PAYARA_HOME / glassfish / domains / lardosmeussonhos / config server, but it did not resolve. can you help me?

This is the exception:
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:59)
	at com.pengrad.telegrambot.TelegramBot.execute(TelegramBot.java:41)
	...
