### ISSUE TITLE
How can I get a text from bot message by msgid?

### ISSUE THREAD

**Issue by Alas-Wallet** [pengrad/java-telegram-bot-api#225]
Hello, How can I get a text from bot message by msgid? If this is not possible, how else can you get the text of the bot message that was sent earlier?

**Comment by pengrad** [comment]
Hi, I suggest you to look for this in Bot API documentation, and then come back here to find that method in this library.
https://core.telegram.org/bots/api#available-methods

AFAIK, there is no method to get message by id.

From what I can think, if you have the chatId where that message was sent, you can forward it to another private chat via `forwardMessage` and in response you will have `Message` object with it's text.
