### ISSUE TITLE
No support for longer (4096 characters+) messages

### ISSUE THREAD

**Issue by Dacaspex** [pengrad/java-telegram-bot-api#226]
**Scenario**
I wish to send a long message using the bot. My message is longer than 4096 characters. 

**Expect**
I expect the bot to send this message successfully, without errors, to the Telegram API.

**Actual**
The bot does not send my message and no exception is thrown. The response does also not give any hints as to why the request was not successfully send and simply gives `SendResponse{result=null}`. 

I suppose it is the case that this scenario has not been implemented. Telegram seems to not allow messages to be longer than 9096 characters. I therefore thought of three possible ways to fix this issue:
- Simply throw an exception when the message is too long and let the calling code (i.e. the user of the library) create a utility to break up the messages.
- Support this, and implement this message splitting utility yourself.
- Let a user set a flag to either throw an exception or let the library solve it for them.

Some resources I found:
- https://core.telegram.org/method/messages.sendMessage
- https://github.com/yagop/node-telegram-bot-api/issues/165
- https://pypi.org/project/telegram-send/#:~:text=Uninstallation-,Usage,smaller%20ones%20and%20sent%20separately.

**Comment by pengrad** [comment]
There are additional fields in response which you can check:
```java
response.isOk()
response.description()
response.errorCode()
```

In your case they will return something like:
 false
Bad Request: message is too long
400

**Comment by Dacaspex** [comment]
Thank you, I could work around the problem with that. If no follow up action will be taken, then this issue can be closed.

**Comment by pengrad** [comment]
don't hesitate to close then
