### ISSUE TITLE
Upgrade OkHttp up to latest version

### ISSUE THREAD

**Issue by galimru** [pengrad/java-telegram-bot-api#228]
Hi

First want to say that I really like this library 🙂

However, I faced with annoying bug which actually an issue on OkHttp library side.
When UpdatesListener is listening for new updates and I'm trying to stop tomcat, it can not be stopped immediately.
It prevents me to redeploy projects because I need while all connections be released.

However this issue was resolved in OkHttp 4.3+, here's related bug https://github.com/square/okhttp/issues/5542

It would be great if you can upgrade OkHttp to latest version to sort out this issue.

**Comment by pengrad** [comment]
Hi!
yes would be a nice improvement. 
if you want to have it faster you can submit a PR too :)
