### ISSUE TITLE
Is using Integer type for User id safe? 

### ISSUE THREAD

**Issue by EXL** [pengrad/java-telegram-bot-api#230]
https://core.telegram.org/bots/api-changelog#march-9-2021

>⚠️**WARNING!** ⚠️
>After one of the upcoming Bot API updates, some user identifiers will become bigger than 2^31 - 1 and it will be no longer possible to store them in a signed 32-bit integer type. User identifiers will have up to 52 significant bits, so a 64-bit integer or double-precision float type would still be safe for storing them. Please make sure that your code can correctly handle such user identifiers.

https://github.com/pengrad/java-telegram-bot-api/blob/82a949b5a2d0a082bf6e988a90514128421c2d9a/library/src/main/java/com/pengrad/telegrambot/model/User.java#L12

**Comment by mircoianese** [comment]
I would say that this needs to be addressed soon. There are also some methods taking Integer as user ID (for example GetChatMember)

**Comment by pengrad** [comment]
thanks @mircoianese updated in 5.2.0
