### ISSUE TITLE
Problems with stopping the telegram bot.

### ISSUE THREAD

**Issue by AlexRassvet** [pengrad/java-telegram-bot-api#232]
Class `com.pengrad.telegrambot.TelegramBot` after call method `setUpdatesListener` create some non daemon threads.
When the application is stopped, such threads interfere with the correct completion of the process. The app stops for a long time.

For solve this problem, need shutdown thread pool in class `okhttp3.OkHttpClient`.

OkHttpClient.dispatcher().executorService().shutdown()

**Comment by AlexRassvet** [comment]
Workaround
This code works, but ugly. The application shutdown time is significantly lower.

`package ...;

import com.pengrad.telegrambot.TelegramBot;
import com.pengrad.telegrambot.impl.TelegramBotClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import okhttp3.OkHttpClient;


import java.lang.reflect.Field;

public class TelegramBotPatch extends TelegramBot {
    private static final Logger LOG = LoggerFactory.getLogger(TelegramBotPatch.class);

    TelegramBotClient apiPatch;

    public TelegramBotPatch(String botToken) {
        super(botToken);
        try {
            final Field apiField = TelegramBot.class.getDeclaredField("api");
            apiField.setAccessible(true);
            this.apiPatch = (TelegramBotClient) apiField.get(this);
            LOG.info("Init TelegramBotClient apiPatch: {}", apiPatch);

        } catch (Exception e) {
            LOG.error("Error get TelegramBotClient", e);
        }
    }

    public void stop(){
        try {
            Field clientF = TelegramBotClient.class.getDeclaredField("client");
            clientF.setAccessible(true);
            OkHttpClient client = (OkHttpClient) clientF.get(apiPatch);

            Field clientWtF = TelegramBotClient.class.getDeclaredField("clientWithTimeout");
            clientWtF.setAccessible(true);
            OkHttpClient clientWt = (OkHttpClient) clientWtF.get(apiPatch);

            if (client != null) {
                stopClient(client);
                if (clientWt != null && client != clientWt) {
                    stopClient(clientWt);
                }
            }
            else {
                if (clientWt != null) {
                    stopClient(clientWt);
                }
            }
        } catch (Exception e) {
            LOG.error("stop bor error", e);
        }
        removeGetUpdatesListener();
    }

    private void stopClient(OkHttpClient client){
        LOG.info("Stop client");
        client.dispatcher().executorService().shutdown();
    }
}
`

**Comment by pengrad** [comment]
Hope `TelegramBot.shutdown()` will help with it, added in 5.2.0

**Comment by aligokalppeker** [comment]
This issue still exists with version 5.3.0. Even if we call the shutdown method, OkHttpClient threads do not exits and process is stuck there.

**Comment by andre77** [comment]
Why is the issue closed, if it still exists?
