### ISSUE TITLE
Error code 110011110?

### ISSUE THREAD

**Issue by hasandiwan** [pengrad/java-telegram-bot-api#240]
final TelegramBot bot = new TelegramBot(this.TELEGRAM_KEY); // obtained from botfather

		// Send messages
		final SendResponse response = bot.execute(new SendMessage(System.currentTimeMillis(), message));
		if (!response.isOk()) {
			ret.clear();
			ret.put("status", Integer.toBinaryString(HttpStatus.URI_TOO_LONG.value()));
			ret.put("error", response.description());
			return ret;
		}
/*
{
  "error": "Not Found",
  "status": "110011110"
}
*/

**Comment by mircoianese** [comment]
Why are you using `System.currentTimeMillis()` as the Chat ID where to send the message to?
