### ISSUE TITLE
Sending message from Telegram Application to a bot

### ISSUE THREAD

**Issue by lfabriko** [pengrad/java-telegram-bot-api#248]
Hello, 
may I ask - is it possible to use this library to send a message from my Telegram Application (api_id, api_hash) to a bot? 

I am searching for java alternative to functionality of Telethon TelegramClient: https://docs.telethon.dev/en/latest/modules/client.html#telegramclient

Thanks for info,
Lucie

**Comment by pengrad** [comment]
This lib is only for bots
