### ISSUE TITLE
Problems with downloading this api

### ISSUE THREAD

**Issue by MogliDerZauberKoenig** [pengrad/java-telegram-bot-api#25]
Hello,

how can i download this api? I saw that i need to use gradle or maven, but how?
Can i use it directly in Eclipse? Can anyone help me or send me a link.

I really dont know how i do this.

**Comment by pengrad** [comment]
Download jar from here
https://oss.sonatype.org/content/repositories/releases/com/github/pengrad/java-telegram-bot-api/1.3.3/java-telegram-bot-api-1.3.3.jar
