### ISSUE TITLE
thumb does not work when send video

### ISSUE THREAD

**Issue by bobogavin** [pengrad/java-telegram-bot-api#252]
SendVideo sendMessage = new SendVideo(chatid, new File(videoFilePath)).thumb(new File(thumbnailFilePath));
        if(caption != null && caption.isEmpty()==false){
            sendMessage.caption(caption);
            sendMessage.parseMode(ParseMode.HTML);
        } 
        if(replyToMessageId != null) sendMessage.replyToMessageId(replyToMessageId);
        if(keyBoard != null) sendMessage.replyMarkup(new InlineKeyboardMarkup(keyBoard));
        SendResponse response = bot.execute(sendMessage);        
        if(response.isOk()==false) return BoolResultT.fails(response.description());
        return BoolResultT.success(response.message());

**Comment by jw-star** [comment]
You can look at this example

https://github.com/jw-star/91pornBot/blob/mas/src/main/java/com/jw/porn/MyAmazingBot.java
