### ISSUE TITLE
ChatAction

### ISSUE THREAD

**Issue by saw1993** [pengrad/java-telegram-bot-api#255]
PLease let me know how to use ChatActions

**Comment by mircoianese** [comment]
```
TelegramBot bot = new TelegramBot(TOKEN);
...
SendChatAction request = new SendChatAction(chatId, ChatAction.typing);
bot.execute(request);
```

Change `ChatAction.typing` with the `ChatAction` you want to send.

**Comment by saw1993** [comment]
> ```
> TelegramBot bot = new TelegramBot(TOKEN);
> ...
> SendChatAction request = new SendChatAction(chatId, ChatAction.typing);
> bot.execute(request);
> ```
> 
> Change `ChatAction.typing` with the `ChatAction` you want to send.

Thank you so much , I am trying to do this so many times
