### ISSUE TITLE
Creating custom requests

### ISSUE THREAD

**Issue by DokanBoy** [pengrad/java-telegram-bot-api#257]
Hello.
How do I create a cast request to the Bot API telegram? For example, I want to create a new chat on behalf of the bot. Can I do this? I found this method in the documentation: https://core.telegram.org/method/messages.createChat. I think it's the right one.

**Comment by mircoianese** [comment]
Hello,

the one you linked is the Core Telegram API, not the BOT API which is what this library supports. 
The Core telegram API is used by Apps / Clients. As far as I know you can't create a new Chat with the BOT API.
