### ISSUE TITLE
how to send menu without text ? 

### ISSUE THREAD

**Issue by 4samitim** [pengrad/java-telegram-bot-api#265]
bot.execute(new SendMessage(update.message().chat().id(), "text")
                        .parseMode(ParseMode.HTML)
                        .disableWebPagePreview(true)
                        .disableNotification(true)
                        .replyMarkup(new ReplyKeyboardMarkup(
                                new String[]{"\uD83C\uDFAE " + "Menu"},
                                new String[]{"\uD83D\uDCF1 " + "Menu2"})
                                .oneTimeKeyboard(true)
                                .resizeKeyboard(true)
                                .selective(true)));

**Comment by mircoianese** [comment]
You can't. A text is mandatory on Telegram when you send a message (even if there are keyboards).
