### ISSUE TITLE
There is a issue with sendMessage with HTML markdown. Could you please fix this. 

### ISSUE THREAD

**Issue by balachandran2b** [pengrad/java-telegram-bot-api#268]
https://github.com/yagop/node-telegram-bot-api/issues/277#issuecomment-409299043

So based on this issue, we need to send the markdown param as a object, instead of a string. I tried setting parseMode in SendMessage request type and it is currently not working.

**Comment by mircoianese** [comment]
Hello, could you please share the code? parseMode is working correctly for me

**Comment by pengrad** [comment]
`.parseMode(ParseMode.HTML)` is working correctly

**Comment by balachandran2b** [comment]
@mircoianese  

Sorry for the incovenience. The issue was with my code.I was using some HTML tags, which are unsupported by telegram. I forgot to close this issue. 

@pengrad  Thank you for this awesome library.
