### ISSUE TITLE
Help needed. UpdateListener doesn't run for callbackQuery

### ISSUE THREAD

**Issue by bestnub** [pengrad/java-telegram-bot-api#272]
I have set up a bot with the latest version (5.7.0) and the examples from the documentation.
It always replies with an inlineKeyboard for testing.
But when pressing the Buttons the updateListener doesn't run.
Only messages trigger the updateListener.
Is this behavior intended and am I using it wrong? If so, how would I use callbackQuerry.

PLS help

            // Register for updates
            telegramBot.setUpdatesListener(updates -> {
                updates.forEach(update -> {
                    log.info("Update:");
                    log.info("callbackQuery: " + String.valueOf(update.callbackQuery()));
                    log.info("inlineQuery: " + String.valueOf(update.inlineQuery()));

                    long chatId = update.message().chat().id();

                    InlineKeyboardMarkup inlineKeyboard = new InlineKeyboardMarkup(
                            new InlineKeyboardButton("url").url("www.google.com"),
                            new InlineKeyboardButton("Callback").callbackData("callback_data"),
                            new InlineKeyboardButton("Switch!").switchInlineQuery("switch_inline_query"));

                    SendMessage request = new SendMessage(chatId, "Choose one:")
                            .replyMarkup(inlineKeyboard);

                    SendResponse sendResponse = telegramBot.execute(request);

                });
                return UpdatesListener.CONFIRMED_UPDATES_ALL;
            });

**Comment by pengrad** [comment]
Your example works fine for me.
Run this script and press "Callback" in TG client, callbackQuery will be returned
