### ISSUE TITLE
Web App not working on KeyboardButton

### ISSUE THREAD

**Issue by tonyalves** [pengrad/java-telegram-bot-api#278]
Hello! 
I was trying to make a button open a web app, like in the documentation of the bot api 6, and it not work. So I check that the field "web_app_info" on KeyboardButton class is not the right according to the documentation. The right name should be just "web_app", in order to get the request done successfully. I made that change locally and it worked.

**Comment by pengrad** [comment]
Hi @tonyalves thank you! Fixed in 6.0.1 release
