### ISSUE TITLE
How to send multiple photos and videos in one message?

### ISSUE THREAD

**Issue by doverchivost** [pengrad/java-telegram-bot-api#279]
I want to send multiple photos and videos (up to 10) in one message with text. Is it possible?
Now I do it like that and it sends each photo and video separately (as expected):

```
            bot.execute(new SendMessage(channelId, msg));
            for (int i = 0; i < mediaCount; i++) {
                if (photo)
                    bot.execute(new SendPhoto(channelId, media));
                else if (video)
                    bot.execute(new SendVideo(channelId, media));
            }
```

**Comment by pengrad** [comment]
Try `SendMediaGroup` https://core.telegram.org/bots/api#sendmediagroup

**Comment by doverchivost** [comment]
Thank you a lot ❤️
Text message is still separate from media, but I'm fine with it
