### ISSUE TITLE
Connection via authenticated proxy

### ISSUE THREAD

**Issue by evnaresh** [pengrad/java-telegram-bot-api#28]
Hi,
    I'm trying to connect to a bot via an authenticated proxy. Could you consider this feature enhancement.
   For now, I have updated the TelegramBotAdapter class to get the authentication working that suits my purpose:

private static OkHttpClient client(Interceptor interceptor, final String proxyHost, final int proxyPort, final String userName, final String password) {
		OkHttpClient.Builder builder = new OkHttpClient.Builder();
		if (interceptor != null) builder.addInterceptor(interceptor);

		final Authenticator proxyAuthenticator = new Authenticator() {
			public Request authenticate(Route route, Response response) throws IOException {
				String credential = Credentials.basic(userName, password);
				return response.request().newBuilder()
						.header("Proxy-Authorization", credential)    
						.build();
			}
		};

		builder.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort)))
		.proxyAuthenticator(proxyAuthenticator)
		.retryOnConnectionFailure(true);

		return builder.build();
	}

**Comment by pengrad** [comment]
Agree. Will add support for custom OkHttpClient.

**Comment by pengrad** [comment]
Added in 2.1.0 version.
`TelegramBotAdapter.buildCustom("token", yourOkHttpClient);`
