### ISSUE TITLE
Неверыныe File_id

### ISSUE THREAD

**Issue by zeahouse** [pengrad/java-telegram-bot-api#283]
При отправке роботу пары фотографий получаю объект PhotoSize[] неверной размерности с одинаковыми File_id для всех элементов массива

![image](https://user-images.githubusercontent.com/70061828/169294710-3bb80a65-5818-4bc2-ae61-c5bdf51248dc.png)

**Comment by pengrad** [comment]
Need to see Telegram responses.
You can try debug mode and paste all HTTP responses here.
If it's how it comes from Telegram API then we can't do anything or maybe need to fix request.
If there is a parsing error then it's a library bug and we will fix it.
