### ISSUE TITLE
How do I enforce users joining a specific channel before using my bot?

### ISSUE THREAD

**Issue by spiritLHLS** [pengrad/java-telegram-bot-api#288]
[How do I enforce users joining a specific channel before using my bot?](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-do-i-enforce-users-joining-a-specific-channel-before-using-my-bot)
↑
Similar to the function of python-telegram-bot above, does java have a similar practice method?
Hopefully there is a way to support the ability to query if a user is in a channel or group.

**Comment by pengrad** [comment]
Yep, just use `GetChatMember` method to check if use is in a channel.
