### ISSUE TITLE
message.document.file_size exception

### ISSUE THREAD

**Issue by bobogavin** [pengrad/java-telegram-bot-api#290]
Run_Win_Bot UpdatesListenerTelegramException : java.io.IOException: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 3871055179 at line 5 column 834 path $.result[3].message.document.file_size
com.pengrad.telegrambot.impl.UpdatesHandler$1.onFailure(UpdatesHandler.java:87)
com.pengrad.telegrambot.impl.UpdatesHandler$1.onFailure(UpdatesHandler.java:49)
com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(TelegramBotClient.java:55)
okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)
![image](https://user-images.githubusercontent.com/17951661/176498391-a70f97bc-cb51-4c14-ba93-91f12ae05a86.png)

**Comment by pengrad** [comment]
All `file_size` fields changed to Long, fixed in 6.1.0 release, thanks to @mircoianese

**Comment by bobogavin** [comment]
> 6.1.0

ok, thanks
