### ISSUE TITLE
This issue still exists with version 6.1.0. Even if we call the shutdown method, OkHttpClient threads do not exits and process is stuck there.

### ISSUE THREAD

**Issue by moscowneversleep** [pengrad/java-telegram-bot-api#291]

**Comment by moscowneversleep** [comment]
#232

**Comment by moscowneversleep** [comment]
use OkHttp version 4.9.3 +

**Comment by pengrad** [comment]
> use OkHttp version 4.9.3 +

This is a potential fix? Don't see any related changes in 4.9.3 changelog

**Comment by moscowneversleep** [comment]
> > 使用 OkHttp 版本 4.9.3 +
> 
> 这是一个潜在的修复？在 4.9.3 更改日志中看不到任何相关更改

use high version. shutdown is work

**Comment by maxim-kukushkin** [comment]
What is the fix for this issue? It's still happening to me when I call `bot.shutdown()` - just an endless stream of exceptions. I use `java-telegram-bot-api 6.3.0`
