### ISSUE TITLE
Bot is unable to delete incoming messages from client

### ISSUE THREAD

**Issue by BowYardAzy** [pengrad/java-telegram-bot-api#296]
Said by Telegram Bot API changelog

> The method [deleteMessage ](https://core.telegram.org/bots/api#deletemessage) can now be used to delete messages sent by a user to the bot in private chats within 48 hours.

I tried with this api but it seems not to support this function.
Am i doing something wrong?

[UPDATE]
Tried better and turned out from it a strange behaviour.
I can delete messages coming from users to the bot's private chat only if it's followed by another message, sent by the bot or the user.

**Comment by pengrad** [comment]
Works as expected, just need to pass correct chatId and messageId
