### ISSUE TITLE
NPE when trying to get the message details

### ISSUE THREAD

**Issue by withpublic** [pengrad/java-telegram-bot-api#299]
I am trying to receive a message id of a published message, 
TelegramBot bot = new TelegramBot(token);
SendResponse response = bot.execute(new SendMessage(channel_id, "Hello!"));

but response.message() is giving NULL, hence NPE when I try to get messageId

**Comment by pengrad** [comment]
You can check if response is OK or message is null:
```java
if (response.isOk()) {
    Integer msgId = response.message().messageId();
} else {
    System.out.println("Bad response: " + response.errorCode() + " " + response.description());
}
```
