### ISSUE TITLE
mark updates as already "read" (or processed)

### ISSUE THREAD

**Issue by hydefus** [pengrad/java-telegram-bot-api#30]
Hi there, congrats for this api, looks pretty easy to use.
this is not an issue but a question. 
Is there any way to mark as already processed the Updates?
Or that logic should be in the bot itself by getting the last "n" events and comparing if they were already processed or not. GetUpdate has a method limit(int) and offset(int), any way to get the updates in reverse order?

best regards

**Comment by pengrad** [comment]
Thanks! 
No special way to mark updates and no way to reverse updates order. 
And i don't think this API needs this. 

If you know last processed update_id, you can simply call getUpdates with update_id + 1.
`An update is considered confirmed as soon as getUpdates is called with an offset higher than its update_id.`

Telegram allows to get only 100 updates in one request, so if you want to get them all  you need to execute getUpdates until it becomes empty. Then combine in one list and use something like `Collections.reverse(allUpdates)`
