### ISSUE TITLE
Documents appear as text files when sent as a media group message.

### ISSUE THREAD

**Issue by UniversalBinary** [pengrad/java-telegram-bot-api#302]
When creating a SendDocument or InputMediaDocument from a byte array, there is no way to specify the content (MIME) type of the data. Although Telegram has automatic content detection, this seems to depend on a filename with a correct extension, which may not always be available if the data you wish to post did not come from a file. Moreover, when creating a list of InputMediaDocument objects to send as a media group message, there is no way to specify a filename.

As you will see from the first screenshot, I have sent three PDF files to a channel as a media group message and as three separate messages, these PDFs have been created from a byte array and no filename was given, as you will see they have all appeared as text files. In the second screenshot, I have set the filename parameter of the SendDocument object to a filename with a .pdf extension when sending the three separate messages and they have displayed correctly. However, as there is no way to set a filename for files when sending them as a media group there is no way to tell Telegram what type of files they are and I cannot get them to display correctly.

It would be helpful if all classes that derive from AbstractMultipartRequest and InputMedia<T> could take the content type in the constructor and use this when uploading the file to Telegram.

![screenshot1](https://user-images.githubusercontent.com/12578186/200174447-b241af6e-70f9-49cf-bb6e-2c0eb26639b7.jpg)
![screenshot2](https://user-images.githubusercontent.com/12578186/200174458-efdda3a5-4741-4145-90ba-afc0492b3823.jpg)

**Comment by pengrad** [comment]
Implemented in 6.3.0 release. 
But setting content type only doesn't work for me, telegram still displays the file by name.
So I also added `setFileName()`. 
It will be correctly set by default from a `File`, but has to be set explicitly for bytes.

https://github.com/pengrad/java-telegram-bot-api/blob/b5616feb0d51d199121100c3cbc8db86081defcb/library/src/test/java/com/pengrad/telegrambot/TelegramBotTest.java#L1534-L1537

Thanks for the issue!
