### ISSUE TITLE
submit many articles

### ISSUE THREAD

**Issue by boyzoon** [pengrad/java-telegram-bot-api#305]
### can you help me to find out why when i use this code the bot does not return any results?

```java

int cont = 0;
InlineQueryResultArticle[] results = new InlineQueryResultArticle[50];

for ( Article article : json.articles ){

results[cont] = new InlineQueryResultArticle(article.id , article.name , article.url).hideUrl(false).description(article.description).thumbUrl(article.iconUrl);
cont++;
        }

bot.execute(new AnswerInlineQuery( message.inlineQuery().id() , results ));
```

### but when i use it this way it works. the problem is that this way I can send only one article and I need to send all those in the "results" variable

```java 
bot.execute(new AnswerInlineQuery( message.inlineQuery().id() , new InlineQueryResult[]{results[0]} ));

**Comment by boyzoon** [comment]
hi?

**Comment by pengrad** [comment]
I don't know why.
The similar test code was working fine.
https://github.com/pengrad/java-telegram-bot-api/blob/9e062c3e68f1706e21c0141090c2e70c442f2661/library/src/test/java/com/pengrad/telegrambot/TelegramBotTest.java#L405

I suggest you to debug API requests and responses and check HTTP logs.
`bot = new TelegramBot.Builder(token()).debug().build();`
