### ISSUE TITLE
InlineKeyboardMarkup not working

### ISSUE THREAD

**Issue by acessors** [pengrad/java-telegram-bot-api#306]
![image](https://user-images.githubusercontent.com/98286101/208789856-ccaf7b2c-852b-49f4-8ff0-2c7156c470a6.png)

![image](https://user-images.githubusercontent.com/98286101/208789903-fa6a9283-aaa5-4c79-a796-10c9972be7cf.png)

InlineKeyboardMarkup is not working.

**Comment by mrProper-666** [comment]
You get 400 from tg
You must set one of the optional fields like callback_data or others from api 
https://core.telegram.org/bots/api#inlinekeyboardbutton
