### ISSUE TITLE
Spark

### ISSUE THREAD

**Issue by Shukik85** [pengrad/java-telegram-bot-api#308]
Не нашел описания по подключению к Maven проекту.
import spark.Request;
import spark.Response;
import spark.Route;

Add to POM.xml

`<!-- https://mvnrepository.com/artifact/com.sparkjava/spark-core -->`
`<dependency>`
`    <groupId>com.sparkjava</groupId>`
`    <artifactId>spark-core</artifactId>`
`    <version>2.9.4</version>`
`</dependency>`

**Comment by pengrad** [comment]
```
<dependency>
  <groupId>com.github.pengrad</groupId>
  <artifactId>java-telegram-bot-api</artifactId>
  <version>6.5.0</version>
</dependency>
```
