### ISSUE TITLE
channel_chat_created is always null

### ISSUE THREAD

**Issue by bobogavin** [pengrad/java-telegram-bot-api#309]
Message field channel_chat_created document is :
Optional. Service message: the channel has been created. This field can't be received in a message coming through updates, because bot can't be a member of a channel when it is created. It can only be found in reply_to_message if someone replies to a very first message in a channel.

so I think when we reply Channel created message, we should receive replied message channel_chat_created is true, but is still null
![image](https://user-images.githubusercontent.com/17951661/215251812-4a261689-ab37-47f6-b952-8807598bdf29.png)

**Comment by pengrad** [comment]
I can only suggest you to debug Telegram API requests and responses and check HTTP logs.
bot = new TelegramBot.Builder(token()).debug().build();

If there is a `channel_chat_created` field in HTTP raw response and library shows it as null then it's a bug and we can fix it.
But if Telegram doesn't send this field then nothing we can do
