### ISSUE TITLE
ChosenInlineResult always null

### ISSUE THREAD

**Issue by ntpan** [pengrad/java-telegram-bot-api#31]
Hello,

could it be that ChosenInlineResult is buggy and always returns null?
I've set it up inside my update loop like this:

`if(update.chosenInlineResult() != null) 
 {
					System.out.println(update.chosenInlineResult().query());
					chatIdResultMapping.remove(update.chosenInlineResult().from().id());
				}`

But it never actually has a value.
Getting normal updates or sending InlineQueryResults is no problem, just getting the ChosenResult always seems to fail.

**Comment by pengrad** [comment]
Hi, good question!
You need to activate feedback about chosen results with sending @Botfather the /setinlinefeedback command.

https://core.telegram.org/bots/inline#collecting-feedback
