### ISSUE TITLE
Error while processing send message.

### ISSUE THREAD

**Issue by Kr1S-D** [pengrad/java-telegram-bot-api#312]
Hello, im using this library on a minecraft plugin, i have registered the update listener that listen for the /chaid command and reply with the chatID of the chat where requested. But i have some problems, when there is an update the bot can "reply" to the messages without any errors or problems.

In my case the plugin in its config has a list with all the chatIds (which are entered by the user) and when I execute the command /telegram hello world!  it should send this message in all the telegram groups / chats it has in that list, but when I do this it doesn't work and adding a debug the response from the telegram servers is SendResponse{result=null} do you know why this happens?

Ps: chats are chats in which the hot has permission to send messages, as it responds to normal commands

**Comment by pengrad** [comment]
I suggest you to debug Telegram API requests and responses and check HTTP logs. 
`bot = new TelegramBot.Builder(token()).debug().build();`

`SendResponse{result=null}` is not telegram logs
