### ISSUE TITLE
The latest version in README should be 6.3.0

### ISSUE THREAD

**Issue by lishali12345** [pengrad/java-telegram-bot-api#315]
When I copied the implementation code in the README doc with version 6.5.0 to my spring project build.gradle, it just can not add the lib to the dependencies. When I found that the latest release and latest tag is 6.3.0, I changed the implementation code version to 6.3.0, then everything is fine.

**Comment by pengrad** [comment]
Sorry for that, 6.5.0 was just released

**Comment by lishali12345** [comment]
I just found it, thanks for the reply.
