### ISSUE TITLE
webApp is not working

### ISSUE THREAD

**Issue by kcejka** [pengrad/java-telegram-bot-api#319]
Hello,
I´m trying to create inline button for shop, but message is not shown.
No error is raised.

`InlineKeyboardButton shop = new InlineKeyboardButton("Shop").webApp(new WebAppInfo("https://revenkroz.github.io/telegram-web-app-bot-example/index.html"));`
`InlineKeyboardMarkup replyMarkup = new InlineKeyboardMarkup().addRow(shop);`
`bot.execute(new SendMessage(CHAT_ID, "Shop TEST").replyToMessageId(message.messageId()).disableWebPagePreview(true).parseMode(ParseMode.HTML).replyMarkup(replyMarkup));`

**Comment by pengrad** [comment]
Works fine for me.
I suggest you to debug Telegram API requests and responses and check HTTP logs.
`bot = new TelegramBot.Builder(token()).debug().build();`
