### ISSUE TITLE
How to change document title?

### ISSUE THREAD

**Issue by MickevichYura** [pengrad/java-telegram-bot-api#32]
There is no method title() in SendDocument (like in SendAudio).
All document have title "file.txt"
![image](https://cloud.githubusercontent.com/assets/9394856/15805418/aa3eaf90-2b32-11e6-88cf-cabd2a2ac0b0.png)

**Comment by pengrad** [comment]
And if use caption() ?

**Comment by MickevichYura** [comment]
Example above with using caption().

**Comment by pengrad** [comment]
Pushed changes in master, will upload to maven this evening.

**Comment by pengrad** [comment]
Done in 2.1.1 as `fileName` parameter for all file requests . 
The default name is the original file name.

`SendDocument request = new SendDocument(chatId, new File(docFile)).fileName("my doc.zip").caption("caption");`
