### ISSUE TITLE
Edit Message

### ISSUE THREAD

**Issue by mzaferanloo** [pengrad/java-telegram-bot-api#33]
How long after sending messages can we edit them?

**Comment by pengrad** [comment]
I dont know. 
For using in app - within 2 days after posting, maybe same for bots

**Comment by mzaferanloo** [comment]
Can we delete our message (for bots)?

**Comment by pengrad** [comment]
Nope

**Comment by mzaferanloo** [comment]
@pengrad Thank you so much :)
