### ISSUE TITLE
Styled text with message entities

### ISSUE THREAD

**Issue by kosik** [pengrad/java-telegram-bot-api#342]
Hello! Telegram has the facility to style text with message entities: https://core.telegram.org/api/entities 

Some of the entities are available as HTML markup: bold, underline, code and others. The total number of Telegram styled objects are 158. Most of them are not available by HTML markup.

As I see, we have _com.pengrad.telegrambot.model.MessageEntity_ class. It seems like with the class should be possible to apply styled text in messages. In fact i did not managed do this. No markup applied. Below is code sample. Could you please advice how to succeed on it:

 As per official documentation:
 _>> A simple, but not very efficient way of computing the entity length is converting the text to UTF-16, and then taking the byte length divided by 2 (=number of UTF-16 code units)._

```

final String message = "00000000000";

final SendMessage request = new SendMessage(chatId, message)
        .parseMode(ParseMode.HTML).disableWebPagePreview(true)
        .disableNotification(true);

final MessageEntity[] msgEntities = new MessageEntity[]{
        new MessageEntity(MessageEntity.Type.phone_number, 0, getOffsetLength(message)) };

request.entities(msgEntities);

telegramBot.execute(request);

private int getOffsetLength(final String msg){
    try {
        final String encoded = new String(msg.getBytes("UTF-8"), "UTF-16");
        final int result = encoded.getBytes().length / 2;
        return result;

    } catch (final Exception e){}
    return 0;
}

```

Thank you in advance for the help

**Comment by pengrad** [comment]
It must be because of the "00000000000" phone number, it doesn't work for me either.
But the number from the telegram doc works fine "+1-212-555-0123".
https://core.telegram.org/bots/api#messageentity

And also "+12125550123". 
It should probably start with a "+"
