### ISSUE TITLE
Stopping the updates listener doesn't cancel running request properly

### ISSUE THREAD

**Issue by DespairScent** [pengrad/java-telegram-bot-api#345]
Stopping updates listener and starting it again in a short time causes two streams of requests to run simultaneously, resulting in ```Update listener error for request {"method":"getUpdates"} with response 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running``` showing continuously.

How to reproduce:
```java
TelegramBot telegramBot = ...;
telegramBot.setUpdatesListener(...);
telegramBot.removeGetUpdatesListener();
telegramBot.setUpdatesListener(...);
```

**Comment by pengrad** [comment]
Thanks, fixed in 6.9.1
