### ISSUE TITLE
Hi，How to set proxy?

### ISSUE THREAD

**Issue by lancyJD** [pengrad/java-telegram-bot-api#358]
![image](https://github.com/pengrad/java-telegram-bot-api/assets/11610702/fa2019fc-7c0f-48ad-969c-ed226d0dc449)

**Comment by kukume** [comment]
Rebuild a new OkhttpClient, it can set proxy in OkhttpClient.Builder, then invoke method TelegramBot.Builder.okHttpClient(OkhttpClient client)
