### ISSUE TITLE
Getting ID through arguments

### ISSUE THREAD

**Issue by scar-day** [pengrad/java-telegram-bot-api#363]
Hello, is there any function that gives user ID through arguments (for example I write like this: /id @<user ID> and it will give ID)

**Comment by mircoianese** [comment]
Hello, if you mean that you need to get the ID of users without using BOTs API then you can use unofficial apps (like Plus Messenger on Android or Nicegram on iOS). You will be able to see the User ID in the User profile.
If you are looking instead to create a Telegram BOT that will send you the of users that starts it, you can do something like this:

```
if (update.message() != null && update.message().text() != null && update.message.text().equals("/start")) {
SendMessage msg = new SendMessage(YOUR_TELEGRAM_ID, "User started the bot: " + update.message().from().id());
bot.execute(msg);
}
```
