### ISSUE TITLE
Consuming callback query

### ISSUE THREAD

**Issue by abangkis** [pengrad/java-telegram-bot-api#37]
Hi, how to consume a callback query from an inline keyboard markup? 

With update, using lastId() +1, will consume the update. With callbackquery, the object still remain.

Thanks.

**Comment by pengrad** [comment]
Hi, what do you mean consume? You want to mark it as processed?

**Comment by abangkis** [comment]
Yes, i want to mark it as processed. So the field will return to null. 

Thanks for the fast reply.

**Comment by pengrad** [comment]
Checking documentation: `An update is considered confirmed as soon as getUpdates is called with an offset higher than its update_id`.

If you use higher offset and old update still remains, maybe it will be removed automatically later. I know this happens with InlineQuery...

**Comment by abangkis** [comment]
Since I'm using timed polling i guess the best practice is to consume the whole update immediately after receiving it. Not waiting till done processing it. I thought there's a way to only consume the callback query.

Thanks
