### ISSUE TITLE
Bot API 7.2

### ISSUE THREAD

**Issue by rufus20145** [pengrad/java-telegram-bot-api#371]
Implement Bot API 7.2 changes
https://core.telegram.org/bots/api#recent-changes

### Integration with Business Accounts

- Added the class [BusinessConnection](https://core.telegram.org/bots/api#businessconnection) and updates about the connection or disconnection of the bot to a business account, represented by the field business_connection in the class [Update](https://core.telegram.org/bots/api#update).
- Added updates about new messages in a business account connected to the bot, represented by the field business_message in the class [Update](https://core.telegram.org/bots/api#update).
- Added updates about message edits in a business account connected to the bot, represented by the field edited_business_message in the class [Update](https://core.telegram.org/bots/api#update).
- Added updates about message deletion in a business account connected to the bot, represented by the class [BusinessMessagesDeleted](https://core.telegram.org/bots/api#businessmessagesdeleted) and the field deleted_business_messages in the class [Update](https://core.telegram.org/bots/api#update).
- Added the method [getBusinessConnection](https://core.telegram.org/bots/api#getbusinessconnection).

### Working on Behalf of Business Accounts

- Added the parameter business_connection_id to the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendSticker](https://core.telegram.org/bots/api#sendsticker), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendLocation](https://core.telegram.org/bots/api#sendlocation), [sendVenue](https://core.telegram.org/bots/api#sendvenue), [sendContact](https://core.telegram.org/bots/api#sendcontact), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [sendDice](https://core.telegram.org/bots/api#senddice), [sendGame](https://core.telegram.org/bots/api#sendgame), and [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup).
- Added the parameter business_connection_id to the method [sendChatAction](https://core.telegram.org/bots/api#sendchataction).
- Added the field business_connection_id to the class [Message](https://core.telegram.org/bots/api#message).
- Added the field sender_business_bot to the class [Message](https://core.telegram.org/bots/api#message).

### Information about Business Accounts

- Added the class [BusinessIntro](https://core.telegram.org/bots/api#businessintro) and the field business_intro to the class [Chat](https://core.telegram.org/bots/api#chat).
- Added the class [BusinessLocation](https://core.telegram.org/bots/api#businesslocation) and the field business_location to the class [Chat](https://core.telegram.org/bots/api#chat).
- Added the classes [BusinessOpeningHours](https://core.telegram.org/bots/api#businessopeninghours) and [BusinessOpeningHoursInterval](https://core.telegram.org/bots/api#businessopeninghoursinterval) and the field business_opening_hours to the class [Chat](https://core.telegram.org/bots/api#chat).

### Mixed-Format Sticker Packs

- Removed the fields is_animated and is_video from the class [StickerSet](https://core.telegram.org/bots/api#stickerset).
- Added the field format to the class [InputSticker](https://core.telegram.org/bots/api#inputsticker).
- Removed the parameter sticker_format from the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).
- Added the parameter format to the method [setStickerSetThumbnail](https://core.telegram.org/bots/api#setstickersetthumbnail).
- Increased the maximum number of stickers in any regular and mask sticker set to 120.
- Allowed to upload WEBM stickers using [SendSticker](https://core.telegram.org/bots/api#sendsticker).

### Request Chat Improvements

- Added the fields request_name, request_username, and request_photo to the class [KeyboardButtonRequestUsers](https://core.telegram.org/bots/api#keyboardbuttonrequestusers).
- Added the fields request_title, request_username, and request_photo to the class [KeyboardButtonRequestChat](https://core.telegram.org/bots/api#keyboardbuttonrequestchat).
- Added the class SharedUser and replaced the field user_ids in the class [UsersShared](https://core.telegram.org/bots/api#usersshared) with the field users.
- Added the fields title, username, and photo to the class [ChatShared](https://core.telegram.org/bots/api#chatshared).

### Other Changes

- Added the field is_from_offline to the class [Message](https://core.telegram.org/bots/api#message).
- Added the field can_connect_to_business to the class [User](https://core.telegram.org/bots/api#user).
- Added the field personal_chat to the class [Chat](https://core.telegram.org/bots/api#chat).
- Added the method [replaceStickerInSet](https://core.telegram.org/bots/api#replacestickerinset),
- Added the class [Birthdate](https://core.telegram.org/bots/api#birthdate) and the field birthdate to the class [Chat](https://core.telegram.org/bots/api#chat).
- Added the field BiometricManager to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps).

**Comment by anfanik** [comment]
Implemented in https://github.com/pengrad/java-telegram-bot-api/pull/372
