### ISSUE TITLE
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException

### ISSUE THREAD

**Issue by RomanPrudkogliad** [pengrad/java-telegram-bot-api#374]
When sharing contacts with bot, I'm getting
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 6111111111 at line 2 column 392 path $.result[0].message.users_shared.user_ids[0]
	at com.recomendo.recomendo.telegram.bot.BotClient.readMessages(BotClient.java:25)

**Comment by RomanPrudkogliad** [comment]
Few lines of fix
[fix_int_in_shared_users_json_serialization.patch](https://github.com/pengrad/java-telegram-bot-api/files/14980713/fix_int_in_shared_users_json_serialization.patch)

**Comment by RomanPrudkogliad** [comment]
See fix in PR https://github.com/pengrad/java-telegram-bot-api/pull/375

**Comment by pengrad** [comment]
Thanks @RomanPrudkogliad, released in 7.2.1
