### ISSUE TITLE
Generate link

### ISSUE THREAD

**Issue by mzaferanloo** [pengrad/java-telegram-bot-api#38]
Hi,
How can I generate a link that has many params, like : https://telegram.me/my_bot?start=14ccf02d25
thank you so much

**Comment by pengrad** [comment]
Hi, i don't understand  what you mean. 
How it depends on Telegram Bot Api?

**Comment by mzaferanloo** [comment]
I saw many bots that they can generate link for send a request, like @villagegamebot
https://telegram.me/VillageGameBot?start=14ccf02d25

**Comment by pengrad** [comment]
So, why you dont want to generate it by yourself?

**Comment by mzaferanloo** [comment]
Because I need to generate links for inviting users in my bot. that was just an example.

**Comment by mzaferanloo** [comment]
I mean how to receive response from of the link

**Comment by pengrad** [comment]
Response will come to you like a normal message. 
Everything is here https://core.telegram.org/bots#deep-linking

**Comment by mzaferanloo** [comment]
so many thanks :)
