### ISSUE TITLE
Unable to parse symbol 'InlineKeyboardButton'

### ISSUE THREAD

**Issue by kuangjianwu** [pengrad/java-telegram-bot-api#393]
![WechatIMG54](https://github.com/user-attachments/assets/67251e33-4d9d-462e-928a-5afc5c2e9611)

![WechatIMG55](https://github.com/user-attachments/assets/407e5df2-2062-4045-b891-795a28ffea14)

**Comment by kuangjianwu** [comment]
<img width="475" alt="image" src="https://github.com/user-attachments/assets/601f63d0-59f2-45d8-98eb-8f251f47d17f">

**Comment by pengrad** [comment]
Please try to re-import library

**Comment by kuangjianwu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by alagiz** [comment]
@kuangjianwu you likely just need to update kotlin version in your Intellij (in Settings -> Languages & Frameworks -> Kotlin)

**Comment by kuangjianwu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
