### ISSUE TITLE
Download files by file path from getFile

### ISSUE THREAD

**Issue by maratkalibek** [pengrad/java-telegram-bot-api#4]
1. Is it write to have method which downloads file.
2. To current realization of TelegramBot interface, there is no way to add method for download files directly (cause of different base urls). Maybe it can be done somehow in retrofit?
3. Maybe define new interface, like TelegramDownload.

**Comment by maratkalibek** [comment]
This will help
http://stackoverflow.com/questions/23279006/dynamic-paths-in-retrofit/23279628#23279628

but only there is need to rewrite all the methods (@GET and @POST) in TelegramBot interface.

**Comment by pengrad** [comment]
Yes, you're right, previous realization was not flexible.
I have changed TelegramBot from interface to class and include Retrofit-interface inside it as BotApi.
For the file operations there is a FileApi class, right now it just concatenates String for the full file url.

I don't think this library should download files. Do you think it can be useful? 
For example on Android it's not interesting, as we have great libraries like Glide and Picasso to download images in context of ImageView using them. In what case do you need to download bytes directly from here?

**Comment by maratkalibek** [comment]
Sorry for late reply,
I think library should realize all the telegram bot functions. Downloading not limited only for photos. There can be also videos and documents.
If you dont' mind, I will write needed code and create pull request for this changes.

Also there is a lot of changes coming with channels, like passing "channelusername" (yes, it is string) as value of chat_id.

**Comment by pengrad** [comment]
Right now I am closing all these changes, but not about channels (bots can be administrators right now), i think how to merge integers and strings better.

And we have tests now :)

What do you mean download only photos? Library just get full URL of any kind of file. And this URL can be downloaded by the user in his special way (as I explained on Android example). 
How do you want to download it? As byte array?

**Comment by pengrad** [comment]
Hey?

**Comment by maratkalibek** [comment]
No difference, as byte array or InputStream.

**Comment by pengrad** [comment]
`InputStream is = new URL(fileUrl).openStream()`
And for complex downloads some complex library can be used, some kind of Apache Commons IO.
I don't think it should be part or dependency of this library.
