### ISSUE TITLE
How to Delete messages of a Channel by Bot admin actor

### ISSUE THREAD

**Issue by azimot** [pengrad/java-telegram-bot-api#42]
Hi , at first i thank you for your easy to use API 
my bot is worked as well by this project , and bot is a administrator of a channel too and i want to delete all posts/messages by every month 
in the telegram API doc i just find this method for that 
https://core.telegram.org/method/messages.deleteMessages
is it possible to do this for cleaning a channel of all posts by Bot or a HTTP request for bot actor or main admin actor ?

**Comment by pengrad** [comment]
Hi, right now its not possible by telegram bot api.
