### ISSUE TITLE
Getting inline updates. Yeah, a new issue.

### ISSUE THREAD

**Issue by stranck** [pengrad/java-telegram-bot-api#44]
Probably that's bad luck, probably that's my bad programmation skill, but I don't get the inline updates.

`GetUpdatesResponse updatesResponse = bot.execute(new GetUpdates().offset(offset));
        	List<Update> updates = updatesResponse.updates();
        	for(Update update : updates) {
        		CallbackQuery callbackQuery = update.callbackQuery();
        	    Message message = update.message();
        	    System.out.println(message.chat().id()+">"+message.text());
        	    System.out.println(callbackQuery.data());
                 }`

Where is _my_ problem? D:

**Comment by pasondag** [comment]
If that can help you, here is how I am doing it. Let me know if you find way to improve. All comments are welcome.

 ```java
        public void run() {
            TelegramBot bot = TelegramBotAdapter.build(token);

            while (true) {
                try {
                    log.info("Checking for updates...");
                    GetUpdatesResponse updatesResponse = bot.execute(
                            new GetUpdates().limit(100).offset(updateId).timeout(LONG_POOLING_TIMEOUT_IN_SECONDS));

                    for (Update update : updatesResponse.updates()) {
                        log.info("Update: " + update);
                        if (update.inlineQuery() != null) {

                                log.info("Inline Query: " + update.inlineQuery().query());

                                InlineQueryResult r1 =
                                        new InlineQueryResultArticle("1", "title", "bla");
                                BaseResponse response =
                                        bot.execute(
                                                new AnswerInlineQuery(
                                                        update.inlineQuery().id(), r1));
                            }
                        }
                        updateId = update.updateId() + 1;
                    }
                } catch (Exception exception) {
                    log.error("Unexpected error", exception);
                }
            }
        }
    }
```

**Comment by stranck** [comment]
Thanks! :D
Tomorrow I will try it and I rewrite here for any problem (Sorry again for my bad english)

**Comment by stranck** [comment]
I resolved using `update.callbackQuery().data()`.
Anyway,  `GetUpdates().limit(100)...` is usless; you can simply write `GetUpdates().offset...`

**Comment by pengrad** [comment]
@stranck Why didnt close issue, if resolved?

**Comment by stranck** [comment]
I forgot lol
