### ISSUE TITLE
sending photo

### ISSUE THREAD

**Issue by MostafaEbrahimi** [pengrad/java-telegram-bot-api#46]
I have problem with sending photo using your API.(I think the problem is by me or generating files)
please see this issue [Issue](https://github.com/MostafaEbrahimi/coderman_bot/issues)
I didn't found another way to communicate with you.

**Comment by pengrad** [comment]
Seems problem with path, I can not help you

**Comment by MostafaEbrahimi** [comment]
Thanks my friend.But now i found that telegram recognize my image as file.
Do you have any idea to solve this problem?
