### ISSUE TITLE
SendDocument didn't change file name and use always file.txt

### ISSUE THREAD

**Issue by pocteg** [pengrad/java-telegram-bot-api#47]
**Steps to reproduce:**

1. Try to use code:

```
public void sendDocument(chanId, byte[] fileBytes){
        File temp = File.createTempFile("My own file name", ".pdf");
        FileUtils.writeByteArrayToFile(temp, fileBytes);

        SendDocument sendDocument = new SendDocument(chatId, temp);
        sendDocument.caption("My own file name caption.pdf");
        bot.execute(sendDocument);

        temp.delete();

}
```
2. Run code
3. Get file with name "file.txt" 

**Expected result:**
File with name "My own file name.pdf" or "My own file name caption.pdf"

**Actual result:**
File with name "file.txt"

**Comment by pocteg** [comment]
Hi @pengrad ,

Thanks for ur library, it's so helpful. Please feel free to write to me if you have any questions.

**Comment by pocteg** [comment]
I'm using version 2.1.1

**Comment by pengrad** [comment]
Hi! 
I can not reproduce. I have correct file name with your code.
Anyway you can explicitly call fileName("my file name") on sendDocument request.
See https://github.com/pengrad/java-telegram-bot-api/issues/32

**Comment by pocteg** [comment]
My bad, using 2.1.0 instead of 2.1.1
