### ISSUE TITLE
No way to check message type.

### ISSUE THREAD

**Issue by BladeZero** [pengrad/java-telegram-bot-api#48]
Hi there,

Usually to check if a message is a reply, forwarded etc we simply have an if statement like this: 
```
if(msg.replyToMessage())
        {
            //stuffs 
        }
        else if(msg.forwardFrom())
        {
            //stufs 
        }
```

However this does not work in java, is there another way to check if a message is of these types that I am missing? 

Regards
BladeZero

**Comment by pengrad** [comment]
`msg.replyToMessage() != null` and `msg.forwardFrom() != null`
