### ISSUE TITLE
exception when proguard is on

### ISSUE THREAD

**Issue by rmesquit** [pengrad/java-telegram-bot-api#49]
Please help.

Exception thrown whenever I try to SendMessage or SendDocument with proGuard on (true)

E: Exception java.lang.Enum$1.create(Enum.java:43)
E: Exception java.lang.Enum$1.create(Enum.java:35)
E: Exception libcore.util.BasicLruCache.get(BasicLruCache.java:54)
E: Exception java.lang.Enum.getSharedConstants(Enum.java:209)
E: Exception java.lang.Enum.valueOf(Enum.java:189)
E: Exception a.l.b(Unknown Source)
E: Exception a.l.a(Unknown Source)
E: Exception a.z.a(Unknown Source)
E: Exception a.a.c.a.a(Unknown Source)
E: Exception a.a.c.a.a(Unknown Source)
E: Exception a.a.b.z.a(Unknown Source)
E: Exception a.a.b.z.b(Unknown Source)
E: Exception a.a.b.z.a(Unknown Source)
E: Exception a.a.b.n.a(Unknown Source)
E: Exception a.ap.a(Unknown Source)
E: Exception a.aq.a(Unknown Source)
E: Exception a.ap.a(Unknown Source)
E: Exception a.ap.a(Unknown Source)
E: Exception com.pengrad.telegrambot.impl.TelegramBotClient.send(Unknown Source)
E: Exception com.pengrad.telegrambot.TelegramBot.execute(Unknown Source)

Proguard:

-keep class com.github.pengrad.** { *; }
-keep class com.github.pengrad.telegrambot.request.** { *; }
-keep class github.pengrad.** { *; }
-keep class github.pengrad.telegrambot.request.** { *; }
-keep class github.pengrad.telegrambot.** { *; }
-keep class java.lang.** { *; }
-keep class java.io.File
-keep class java.io.*
-keep class java.io.** { *; }
-keep class java.lang.reflect.Type
-keep class java.util.HashMap
-keep class java.util.Map
-keepclassmembers,allowoptimization enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keep class com.google.** { *; }
-keep class com.pengrad.telegrambot.** { *; }
-keep class com.pengrad.** { *; }

Thank you

**Comment by pengrad** [comment]
Hi, please try to add

-keep class com.pengrad.telegrambot.response.** { *; }
-keep class com.pengrad.telegrambot.model.** { *; }

**Comment by rmesquit** [comment]
Thank you for the quick response. Unfortunately, the problem persists. Maybe there is something wrong in the way that I am calling the Bot?

        Runnable telegram = new Runnable() {

            @Override
            public void run() {
                try{
                   
                    TelegramBot bot = TelegramBotAdapter.build("XXXXXX");
                    SendResponse sendD = bot.execute(new SendMessage("XXXX", "MyMessage");
                
                }catch(Exception e){
                    Log.e("Log", "Telegram Bot exception ");
                    for(int x = 0 ; x < e.getStackTrace().length; x++){
                        Log.e("LogInfo", "Exception " + e.getStackTrace()[x]);
                    }
                }
            }
        };
        Thread runTel = new Thread(telegram);
        runTel.start();

**Comment by pengrad** [comment]
Everything looks fine with your code. 
But you can always try to test it without proguard. 
If it's ok, you can use mapping to exactly find where is the problem. 

Oh, i have  just found this solution on SO http://stackoverflow.com/questions/20651575/android-release-apk-crash-with-java-lang-assertionerror-impossible-in-java-lang
Maybe will help you
```
# For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations 
-keepclassmembers enum * { 
    public static **[] values(); 
    public static ** valueOf(java.lang.String);
 }
```


Суббота, 3 сентября 2016 г., 0:48 +0700 от rmesquit  < notifications@github.com >:
>Thank you for the quick response. Unfortunately, the problem persists. Maybe there is something wrong in the way that I am calling the Bot?
>    Runnable telegram = new Runnable() {

        @Override
        public void run() {
            try{

                TelegramBot bot = TelegramBotAdapter.build("XXXXXX");
                SendResponse sendD = bot.execute(new SendMessage("XXXX", "MyMessage");

            }catch(Exception e){
                Log.e("Log", "Telegram Bot exception ");
                for(int x = 0 ; x < e.getStackTrace().length; x++){
                    Log.e("LogInfo", "Exception " + e.getStackTrace()[x]);
                }
            }
        }
    };
    Thread runTel = new Thread(telegram);
    runTel.start();

**Comment by rmesquit** [comment]
I think I didn't import your library correctly. I renamed the package names to match my own app's. It works just fine without proGuard. I am not familiar with the concept of 'use mapping to exactly find where is the problem' . I thought LogCat was the way to do it... I will keep digging.

**Comment by pengrad** [comment]
Proguard generate mapping.txt in build directory. 
I am sorry, i can not test it until next Friday. 
I think you should keep digging around enums and proguard, stacktrace looks like problem in there

**Comment by rmesquit** [comment]
Thank you! Have a great weekend.

**Comment by rmesquit** [comment]
So here is what solved the problem. Initially I had tried:
-keepclassmembers,allowoptimization enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

however, as you suggested, the correct one is

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
 }

Now I am getting a simpler error: SendResponse{result=null} I will update this comment once I have everything working. Just wanted to let you know that I am making progress!

**Comment by rmesquit** [comment]
[Resolved] 

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
 }

-keep class com.pengrad.telegrambot.** { *; }
