### ISSUE TITLE
Incompatible chat id types

### ISSUE THREAD

**Issue by Tillerino** [pengrad/java-telegram-bot-api#5]
`Chat.id()` is of type `Long`, but all `TelegramBot.send*()` methods have `Integer` as the first argument. Not only do you have to cast the id, which is already annoying enough, but because both types are boxed, you have to do a double cast:

`bot.sendWhatever((int) (long) Chat.id(), ...)`

The [specification](https://core.telegram.org/bots/api#chat) says that the id field of the Chat type is an integer, so maybe `Chat.id` should be changed?

**Comment by pengrad** [comment]
Yes, you are right about Integer, but it doesn't say about Java's Integer. 
Here is a description of the Chat object: **Unique identifier for this chat, not exceeding 1e13 by absolute value**. And it's not an Integer, it's a Long. 

So, I think I should change all Integer fields to Long, as 2 billions it's not enough. Probably Telegram use Integer as Int64. What do you think?

And of course, there is no need to cast `bot.send( longChatId.intValue() )`

**Comment by maratkalibek** [comment]
I think Integer is right choice.

cause in documentation - It is safe to use 32-bit signed integers for storing all Integer fields unless otherwise noted.

**Comment by maratkalibek** [comment]
everywhere must be used Integer type unless otherwise noted...
you must return to Integer.

**Comment by pengrad** [comment]
@maratkalibek  thanks, I was just looking for this is documentation..
But for chat_id the otherwise is noted – it's a Long. 
And all send* methods should use Long too.

**Comment by Tillerino** [comment]
@pengrad I agree. Or maybe just use `long` instead of `Long`?

**Comment by maratkalibek** [comment]
@pengrad hmmm, I'm looking here - https://core.telegram.org/bots/api#sendmessage

**Comment by maratkalibek** [comment]
where it is specified that is have to be long?
as I know, there is negative values for groups and positive for users.

**Comment by pengrad** [comment]
Just read Chat object description

**Comment by pengrad** [comment]
@Tillerino I decided not to use primitives to allow null

**Comment by maratkalibek** [comment]
sorry, was my fault.
@pengrad @Tillerino maybe start using String for send* chat_id parameters?

**Comment by pengrad** [comment]
I am actually thinking how to support Integer for chats and String for channels. But using String for everything it's not a good solution.
