### ISSUE TITLE
One Message incoming twice

### ISSUE THREAD

**Issue by Turael** [pengrad/java-telegram-bot-api#50]
Hey everyone,

I test a bit with that api in combination with Spring and I may found a bug or something?
I have a Scheduled Bean with a fixedRate by 500ms - so every 500ms spring is calling that method.
The rest of that method is like your example but if i write to the bot a bit faster then I get 2 messages with the same messageId... (see picture)

`
GetUpdatesResponse updatesResponse = bot.execute(new GetUpdates().limit(0).offset(0).timeout(0));
		List<Update> updates = updatesResponse.updates();

		// Collections.reverse(updates); // is that needed? 
		for (Update update : updates) {

			Message message = update.message();
			Chat chat = message.chat();
			User user = message.from();

			if (message.text() != null) {
				System.out.println("New message: " + message.text() + " id: " + message.messageId() + " from " + chat);
				SendResponse sendResponse = bot.execute(new SendMessage(chat.id(), "Selber: " + message.text()));

			}
		}
`
[Picture](http://storage9.static.itmages.com/i/16/0909/h_1473440458_8779347_8551eafd8c.png)
Terminaloutput and picture are not the same - it can reproduce...

Terminaloutput:

- New message: 1 id: 1005 from Chat{id=5..., type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 1 id: 1005 from Chat{id=5..., type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 2 id: 1008 from Chat{id=..., type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 3 id: 1010 from Chat{id=..,, type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 3 id: 1010 from Chat{id=...,, type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 4 id: 1013 from Chat{id=...,, type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 5 id: 1015 from Chat{id=..., type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 5 id: 1015 from Chat{id=..., type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 6 id: 1018 from Chat{id=..., type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 7 id: 1020 from Chat{id=..., type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 8 id: 1022 from Chat{id=..., type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}
- New message: 9 id: 1024 from Chat{id=..., type=Private, first_name='Domme', last_name='null', username='Turael', title='null'}

**Comment by pengrad** [comment]
Hi, you should increment offset parameter. 
See https://github.com/pengrad/java-telegram-bot-api/issues/30

**Comment by Turael** [comment]
ah thanks for that fast response - ok it works now :)
Now i understand your [Testclass](https://github.com/pengrad/java-telegram-bot-api/blob/master/src/test/java/com/pengrad/telegrambot/TestLoopGetUpdates.java)
