### ISSUE TITLE
Can not get high scores from game

### ISSUE THREAD

**Issue by danielbronder** [pengrad/java-telegram-bot-api#53]
I am trying to receive the high scores from the game called LumberJack. I am trying to use your suggestion with GetGamHighScoreResponse. But I get an error message telling me that he found a GetWebHookINfoResponse instead od GetGameHighScoreResponse.

Here is my code:

```
 GetGameHighScoresResponse highScoresResponse = telegramBot.execute(
new GetGameHighScores(55427529, updates.get(2).message().chat().id(), 5));

GameHighScore[]  scores = highScoresResponse.result();

System.out.println(scores);
```
This should work, but it doesn't. I hope you can fix this little bug in the next release or snapshot.

**Comment by pengrad** [comment]
Thanks!
Fixed in 2.1.4
