### ISSUE TITLE
Is it possible to set high score in existing game?

### ISSUE THREAD

**Issue by danielbronder** [pengrad/java-telegram-bot-api#54]
Hi I am trying to cheat on an existing game. 
I know it is not very good from me. You are telling is that it is possible to set a high score from a game. I am following your code, but I get a message telling me that Game score can't be set. So is it even possible to set a high score for a game or did telegram block this function.

If anyone wants to see my code, here it is:

```
SetGameScore setGameScore = new SetGameScore(55427529, 1000, 55427529, 5);
SendMessage sendMessage = new SendMessage(55427529, "Testing sendMessage");

BaseResponse response = telegramBot.execute(setGameScore);
SendResponse sendResponse = telegramBot.execute(sendMessage);

System.out.println("Response sendGame: " + response.errorCode() + "\t" +response.description());
System.out.println("Response sendMessage: " + sendResponse.errorCode() + "\t" + sendResponse.description());
```

This is my response:

```
Response sendGame: 400	Bad Request: Game score can't be set
Response sendMessage: 0	null
```

The sendMessage does work, but the setGameHighScore doesn't.

Hope you can help me.

**Comment by pengrad** [comment]
Hi, you can only set score for your own bot's games.

**Comment by danielbronder** [comment]
@pengrad That makes sense.
