### ISSUE TITLE
Instances stacking?

### ISSUE THREAD

**Issue by jm-jimenez** [pengrad/java-telegram-bot-api#55]
I am starting doing very basic things as I am a beginner with Telegram Bots.

I am using NetBeans IDE for development. I have an issue every time I run the program. For example, let's suppose I have the next code:

```java
Message message;
User user;
Chat chat;
SendMessage sendMessage;

int offset = 0;

while (true){
    getUpdates = new GetUpdates().offset(offset);
    getUpdatesResponse = bot.execute(getUpdates);
    updates = getUpdatesResponse.updates();
    for (Update u : updates){
        offset = u.updateId()+1;
        message = u.message();
        user = message.from();
        chat = message.chat();
        sendMessage = new SendMessage(chat.id(), "Welcome " + user.firstName());
        bot.execute(sendMessage);
    }
}

```

When I send a message to the bot, it responds "Welcome myuser". If now, I stop the program and I change the sendMessage to

`sendMessage = new SendMessage(chat.id(), "Goodbye " + user.firstName());`

and i run the program again, when I text to the bot it responds:
"Welcome myuser
Goodbye myuser"

If I continue stopping and running again, the number of msgs I receive when I send a message continues increasing.

Is there something I'm missing? How can I stop the other instances or whatever they are?

Thanks for your help and your work

**Comment by pengrad** [comment]
Hi, when you starting again your `offset` is 0. 
That's why you receive old messages. 
Try to save offset somewhere and load every time when you starting the program.

**Comment by jm-jimenez** [comment]
Ok, when it starts again, it's 0. Buf if I send two messages... wouldn't it update the offset to first update's id + 1?

Besides, if I stop all the running programs, the bot is still responding with all the stack of messages. Is it suppose to work even when I have no programs running?

**Comment by pengrad** [comment]
No, if bot is still responding means you have some running programs

**Comment by jm-jimenez** [comment]
I stopped all the programs and even exit from netbeans... the bot was still responding! I reset the computer and finally the bot stopped. I'll dig deeper in to this.
