### ISSUE TITLE
Is it possible to open a Telegram game?

### ISSUE THREAD

**Issue by danielbronder** [pengrad/java-telegram-bot-api#56]
I have a question about the Telegram games. There is a simple telegram game called LumberJack. Is it possible to open or maybe play the game in java? Or can we only get the available variables from the game?

**Comment by pengrad** [comment]
Sorry, I don't understand quesition. 
I can only help you with specific problems in this API

**Comment by danielbronder** [comment]
You have a game from telegram called LumberJack. Is it possible to open this game?
So you can see the gif/picture etc

**Comment by pengrad** [comment]
No, they dont have such api
