### ISSUE TITLE
proxy Issue

### ISSUE THREAD

**Issue by DenisWpk** [pengrad/java-telegram-bot-api#57]
Hi! 

Can I use your library with https proxy server? Not http and https.   

Thank you for response.

**Comment by pengrad** [comment]
Hi! 
Yes, you can

**Comment by DenisWpk** [comment]
Can you show example of code using https proxy?

**Comment by pengrad** [comment]
Give me exact problem you have

**Comment by DenisWpk** [comment]
I want send messages and receive answeres through https proxy server. Not directly and using https server. 
I use another library for creating bots and it has follow code for connect through proxy:
bot.getOptions().setProxyHost("10.20.80.19");
bot.getOptions().setProxyPort(3128);

But it work only for http proxy.

**Comment by pengrad** [comment]
Ok, not sure https will work, but you can try to play with OkHttpClient used in this api, maybe you will find option to use https in it.
See https://github.com/pengrad/java-telegram-bot-api/issues/28

**Comment by DenisWpk** [comment]
Ок. Thank you. Спасибо)

**Comment by DenisWpk** [comment]
Hi!
I test your library with https proxy. It works well. Thank you.
