### ISSUE TITLE
Ignore unknown properties at json de- and serialization 

### ISSUE THREAD

**Issue by monstah** [pengrad/java-telegram-bot-api#59]
hey hey, 

at first, thanks for this great repo, I have been using it a several times, but I also have been into trouble a couple of times, because I used your nice wrapper with SpringBoot and/or Dropwizard (I think they are using Jackson for the deserialization and serialization of the json-stuff). Unfortunately It can not parse most of the responses, due to missing properties in the json-request/response, so I always have to make my own POJOs. Maybe you could just add a certain annotation called `@JsonIgnoreProperties(ignoreUnknown=true)`  [link](https://fasterxml.github.io/jackson-annotations/javadoc/2.6/com/fasterxml/jackson/annotation/JsonIgnoreProperties.html) to the model-classes, at least that is, what I do with my own POJOs to get it working. Thanks for your time.

**Comment by pengrad** [comment]
Hi, how exactly you are using it? 
I have built-in GSON that parses everything without problems.
If you need to parse Update object from Webhook, this is for you:
``` java
Update update = BotUtils.parseUpdate(stringRequest); // from String
Update update = BotUtils.parseUpdate(reader); // or from java.io.Reader
```

**Comment by pengrad** [comment]
@monstah  ??

**Comment by monstah** [comment]
I will try to provide you a good example today

**Comment by monstah** [comment]
for example, this is my own Chat-POJO for Spring or Dropwizard, because they are using the Jackson Parser which seems to throw an error, when there are Properties in the JSON, that are not "covered" by the POJO. 
I hope this link works, the github formatting did not work: http://collabedit.com/4scs3 

> Hi, how exactly you are using it?

Furthermore I am using your POJOs in a POST method in Spring, that is called by the telegram webhook, but it automatically uses Jackson instead of GSON to parse it. I am wondering, if no one else ran into the same trouble as me. You just need to add the `@JsonIgnoreProperties(ignoreUnknown=true)` at class-scope. At least this fixed my problems in the past. 

Alternatively, I can fork and add it by myself. I would add [lombok-support](https://projectlombok.org/)
 either way.

What do you think?

**Comment by pengrad** [comment]
Just adding this line is not a problem. 
I don't want to add another dependency just for one annotation.
So, we can move whole library to jackson, or you can tune your Spring config :)

Maybe you can take not these POJOs but String object in Spring post methods. After that you parse it same I mentioned above.

Or you can change jackson config in Spring, like this http://stackoverflow.com/questions/14343477/how-do-you-globally-set-jackson-to-ignore-unknown-properties-within-spring

About lombok - you can play with it, but I think you can not add it without jackson.

**Comment by monstah** [comment]
Heya, 

yea, after posting this, I came to the same results. Adding another dependency would suck. Unfortunately I haven't checked for setting the Jackson prop global. Nevermind, I think, I will try the global setting with lombok and let you know. In general I have no problems with Gson, but somehow I prefer Jackson.
