### ISSUE TITLE
Please add some useful documentation

### ISSUE THREAD

**Issue by diegomariani** [pengrad/java-telegram-bot-api#6]
Is not quite easy and fast use this library without any kind of documentation. I hope you can provide some documentation out there. Anyway, thank you so much for this library.

**Comment by pengrad** [comment]
I am totally agree, documentation is needed. 
Could you tell me please, what was the hardest part for you to start using this library? 
Thanks!

**Comment by diegomariani** [comment]
Yes, I have to check the source code to know which types are returned by some methods, or which params I have to pass to some methods. Would be awesome if you can build some examples too (how to handle updates, messages and so on).

keep up the good work

**Comment by pengrad** [comment]
Thanks, will try to do something :)

**Comment by pengrad** [comment]
Take a look at current README. 
I didn't describe some obvious methods. 
But all complex details should be covered
