### ISSUE TITLE
hide keyboard

### ISSUE THREAD

**Issue by DenisWpk** [pengrad/java-telegram-bot-api#63]
Hi! 

How I can hide keyboard after sending message? 

Thanx for help!

**Comment by pengrad** [comment]
Use `ReplyKeyboardRemove` keyboard or `replyKeyboardMarkup.oneTimeKeyboard(true)` when sending message

**Comment by DenisWpk** [comment]
ReplyKeyboardRemove not exist. 
replyKeyboardMarkup.oneTimeKeyboard(true) not hide keyboard.

**Comment by pengrad** [comment]
ReplyKeyboardRemove available in new version. Before we had ReplyKeyboardHide

**Comment by DenisWpk** [comment]
i use old version. 

Thank you )

**Comment by DenisWpk** [comment]
Unfortunately I could not hide standart keyboard (with letters and numbers) after sending response. 

There is my code: 

Keyboard replyKeyboardHide = new ReplyKeyboardRemove(false);
SendMessage request = new SendMessage(message.from().id(), text).parseMode(ParseMode.HTML).disableWebPagePreview(false).disableNotification(true).replyMarkup(replyKeyboardHide );
bot.execute(request);

**Comment by pengrad** [comment]
You can't remove standart keyboard, only custom one. 
Please read telegram bot api docs. 

> ReplyKeyboardRemove
Upon receiving a message with this object, Telegram clients will remove the current custom keyboard and display the default letter-keyboard. By default, custom keyboards are displayed until a new keyboard is sent by a bot. An exception is made for one-time keyboards that are hidden immediately after the user presses a button (see ReplyKeyboardMarkup).
