### ISSUE TITLE
setGetUpdatetsListener deprecated?

### ISSUE THREAD

**Issue by eljosemari** [pengrad/java-telegram-bot-api#64]
Hi,

Why setGetUpdatetsListener is marked as deprecated at last version?

Thanks in advance.

**Comment by pengrad** [comment]
Hi,
There was stupid typo from me in **setGetUpdateTsListener**.
So, correct method is `setUpdatesListener`.
Same with `GetUpdatesListener` and `UpdatesListener`

And thanks for noticing, i will update docs
