### ISSUE TITLE
Edit Message

### ISSUE THREAD

**Issue by DenisWpk** [pengrad/java-telegram-bot-api#67]
Hi! 

How I can stop reception update.callbackQuery().data() from server or clear it? 
I using long polling bot. When I press button Text1 on inlineKeyboard I change message text on New text1. When I press button Text2 on inlineKeyboard I change message text on New text2.
But server continues pass update.callbackQuery().data() from first button and second button and text message switch to New text1 and New text2 every second. 

Where I wrong? My code below
bot = TelegramBotAdapter.buildCustom(token, client);

			while (true) {
				bot.execute(new GetUpdates().limit(100).offset(updateId.get()).timeout(LONG_POOLING_TIMEOUT_IN_SECONDS),
						new Callback<GetUpdates, GetUpdatesResponse>() {

							@Override
							public void onResponse(GetUpdates request, GetUpdatesResponse response) {
								if (response.updates() != null) {

									for (Update update : response.updates()) {

										if (update.callbackQuery() != null) {
											try {
												handleIncomingMessageInline(update);
											} catch (ClassNotFoundException | SQLException e) {
												e.printStackTrace();
											}
										} 
											updateId.set(update.updateId());
											break;
										}
									}
								}
							}

							@Override
							public void onFailure(GetUpdates request, IOException e) {
								e.printStackTrace();
							}
						});

				Thread.sleep(LONG_POOLING_TIMEOUT_IN_SECONDS * 1000);
			}
private void handleIncomingMessageInline(Update update) throws ClassNotFoundException, SQLException {

			if (update.callbackQuery().data().equals("my_data1")) {
				InlineKeyboardMarkup inlineKeyboard = new InlineKeyboardMarkup(
						new InlineKeyboardButton[] { new InlineKeyboardButton("Text1").callbackData("my_data1"),
								new InlineKeyboardButton("Text2").callbackData("my_data2") });
				EditMessageText editMessageText = new EditMessageText(update.callbackQuery().message().chat().id(),
						update.callbackQuery().message().messageId(), "New text1").parseMode(ParseMode.HTML)
								.disableWebPagePreview(true).replyMarkup(inlineKeyboard);
				bot.execute(editMessageText);
			} else if (update.callbackQuery().data().equals("my_data2")) {
				InlineKeyboardMarkup inlineKeyboard = new InlineKeyboardMarkup(
						new InlineKeyboardButton[] { new InlineKeyboardButton("Text1").callbackData("my_data1"),
								new InlineKeyboardButton("Text2").callbackData("my_data2") });
				EditMessageText editMessageText = new EditMessageText(update.callbackQuery().message().chat().id(),
						update.callbackQuery().message().messageId(), "New text2").parseMode(ParseMode.HTML)
								.disableWebPagePreview(true).replyMarkup(inlineKeyboard);
				bot.execute(editMessageText);
			}

Thanks for your response.

**Comment by pengrad** [comment]
Maybe adding `+1` here `updateId.set(update.updateId() + 1);` will help you.

Please, next time try to paste your code more carefully, impossible to read this.
Thank you!

**Comment by pengrad** [comment]
Btw, new `UpdatesListener` can do long pooling job for you.

```java
bot.setUpdatesListener(new UpdatesListener() {
    @Override
    public int process(List<Update> updates) {

        // process updates

        return UpdatesListener.CONFIRMED_UPDATES_ALL;
    }
});
```

**Comment by pengrad** [comment]
@DenisWpk Any feedback?

**Comment by DenisWpk** [comment]
@pengrad sorry for my code. 
Yes, I lose +1, my mistake.

Thank you!
