### ISSUE TITLE
Send Video

### ISSUE THREAD

**Issue by sebdei** [pengrad/java-telegram-bot-api#70]
Hey,
could you explain how I can send some videos with a specific URL for example a youtube video?

I expected I can send it the same way as sending a photo.
```
SendPhoto sendPhoto = new SendPhoto(chatID,"http//:APhoto.org");
TelegramBot bot = TelegramBotAdapter.build("token");

bot.execute(sendPhoto);
```

My Expectation:
```
String url = "https://www.youtube.com/watch?v=S9bCLPwzSC0";
SendVideo sendVideo = new SendVideo(chatID, url);

bot.execute(sendVideo);
```

Thanks for your reply.

**Comment by pengrad** [comment]
I dont know how to send Youtube video and telegram docs don't say anything about it.
https://core.telegram.org/bots/api#sendvideo

But you can send url with video file:
`SendResponse sendResponse = bot.execute(new SendVideo(chatId, "http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4"));`

**Comment by sebdei** [comment]
Ok, youtube videos is a special case and I didn't find out how you can link to the specific video file.
Thank you!
