### ISSUE TITLE
Load circle in inlinemessage

### ISSUE THREAD

**Issue by DenisWpk** [pengrad/java-telegram-bot-api#72]
Hi! 

When I tap on inline button circle load is appearing and stay visible several seconds.
How i can hide this circle after button tapped.
Attach image.
Thank you.
![1c24fa2e-c734-45e3-b605-e9a64273dde3](https://cloud.githubusercontent.com/assets/8546089/22364552/210436e8-e494-11e6-98da-5e2dec9df189.jpg)

**Comment by pengrad** [comment]
Denis, it is not an issue of this project and this place is not a telegram support. 
Please ask such questions on Stackoverflow or bot support chat.

**Comment by ali-bagheri** [comment]
use this

AnswerCallbackQuery answer = new AnswerCallbackQuery(callbackQuery.id());
		bot.execute(answer);
