### ISSUE TITLE
Why not work?

### ISSUE THREAD

**Issue by shahinesi** [pengrad/java-telegram-bot-api#75]
`

```
             BOT_TOKEN = "MyToken*****";
        chatId = "@textion_me";
        bot = TelegramBotAdapter.build(BOT_TOKEN);      
 SendMessage request = new SendMessage(chatId,"Test")
                            .parseMode(ParseMode.HTML)
                            .disableWebPagePreview(true)
                            .disableNotification(true)
                            .replyToMessageId(1)
                            .replyMarkup(new ForceReply());
                    // sync
                    SendResponse sendResponse = bot.execute(request);
                    boolean ok = sendResponse.isOk();
                    Message message = sendResponse.message();
                    Log.e("TRT",ok +"");
                    // async
                    bot.execute(request, new Callback<SendMessage, SendResponse>() {
                        @Override
                        public void onResponse(SendMessage request, SendResponse response) {

                        }

                        @Override
                        public void onFailure(SendMessage request, IOException e) {

                        }
                    });
```

`

**Comment by pengrad** [comment]
What doesn't work?

**Comment by shahinesi** [comment]
I do not know .
Normal mode that I work with API text message!
Now when I send a message with the code, nothing happens!
I do not know the reason.
Please guide me where the problem is.
The "MyToken *****" token is entered correctly.

**Comment by pengrad** [comment]
Try `TelegramBotAdapter.buildDebug` and check console

**Comment by shahinesi** [comment]
3-26 18:49:54.462 19741-19741/ir.channelyar.telegrambot D/ViewRootImpl: ViewPostImeInputStage processPointer 0
03-26 18:49:54.572 19741-19741/ir.channelyar.telegrambot D/ViewRootImpl: ViewPostImeInputStage processPointer 1
03-26 18:49:54.602 19741-19741/ir.channelyar.telegrambot D/OkHttp: --> POST https://api.telegram.org/bot373381534:AAEtYPzduCbY05LAUWP0uEobg1TYyAb5ibA/sendMessage http/1.1
03-26 18:49:54.602 19741-19741/ir.channelyar.telegrambot D/OkHttp: Content-Type: application/x-www-form-urlencoded
03-26 18:49:54.602 19741-19741/ir.channelyar.telegrambot D/OkHttp: Content-Length: 195
03-26 18:49:54.602 19741-19741/ir.channelyar.telegrambot D/OkHttp: reply_to_message_id=1&text=Test&parse_mode=HTML&reply_markup=%7B%22force_reply%22%3Atrue%2C%22selective%22%3Afalse%7D&disable_web_page_preview=true&chat_id=%40textion_me&disable_notification=true
03-26 18:49:54.602 19741-19741/ir.channelyar.telegrambot D/OkHttp: --> END POST (195-byte body)
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: <-- 400 Bad Request https://api.telegram.org/bot373381534:AAEtYPzduCbY05LAUWP0uEobg1TYyAb5ibA/sendMessage (180ms)
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Server: nginx/1.10.0
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Date: Sun, 26 Mar 2017 14:19:51 GMT
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Content-Type: application/json
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Content-Length: 83
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Connection: keep-alive
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Access-Control-Allow-Origin: *
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: {"ok":false,"error_code":400,"description":"Bad Request: inline keyboard expected"}
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: <-- END HTTP (83-byte body)
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot E/TRT: false
03-26 18:49:54.782 19741-21183/ir.channelyar.telegrambot D/OkHttp: --> POST https://api.telegram.org/bot373381534:AAEtYPzduCbY05LAUWP0uEobg1TYyAb5ibA/sendMessage http/1.1
03-26 18:49:54.782 19741-21183/ir.channelyar.telegrambot D/OkHttp: Content-Type: application/x-www-form-urlencoded
03-26 18:49:54.782 19741-21183/ir.channelyar.telegrambot D/OkHttp: Content-Length: 195
03-26 18:49:54.782 19741-21183/ir.channelyar.telegrambot D/OkHttp: reply_to_message_id=1&text=Test&parse_mode=HTML&reply_markup=%7B%22force_reply%22%3Atrue%2C%22selective%22%3Afalse%7D&disable_web_page_preview=true&chat_id=%40textion_me&disable_notification=true
03-26 18:49:54.782 19741-21183/ir.channelyar.telegrambot D/OkHttp: --> END POST (195-byte body)
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: <-- 400 Bad Request https://api.telegram.org/bot373381534:AAEtYPzduCbY05LAUWP0uEobg1TYyAb5ibA/sendMessage (159ms)
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Server: nginx/1.10.0
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Date: Sun, 26 Mar 2017 14:19:52 GMT
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Content-Type: application/json
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Content-Length: 83
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Connection: keep-alive
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Access-Control-Allow-Origin: *
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: {"ok":false,"error_code":400,"description":"Bad Request: inline keyboard expected"}
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: <-- END HTTP (83-byte body)

**Comment by shahinesi** [comment]
`3-26 18:49:54.462 19741-19741/ir.channelyar.telegrambot D/ViewRootImpl: ViewPostImeInputStage processPointer 0
03-26 18:49:54.572 19741-19741/ir.channelyar.telegrambot D/ViewRootImpl: ViewPostImeInputStage processPointer 1
03-26 18:49:54.602 19741-19741/ir.channelyar.telegrambot D/OkHttp: --> POST https://api.telegram.org/bot373381534:AAEtYPzduCbY05LAUWP0uEobg1TYyAb5ibA/sendMessage http/1.1
03-26 18:49:54.602 19741-19741/ir.channelyar.telegrambot D/OkHttp: Content-Type: application/x-www-form-urlencoded
03-26 18:49:54.602 19741-19741/ir.channelyar.telegrambot D/OkHttp: Content-Length: 195
03-26 18:49:54.602 19741-19741/ir.channelyar.telegrambot D/OkHttp: reply_to_message_id=1&text=Test&parse_mode=HTML&reply_markup=%7B%22force_reply%22%3Atrue%2C%22selective%22%3Afalse%7D&disable_web_page_preview=true&chat_id=%40textion_me&disable_notification=true
03-26 18:49:54.602 19741-19741/ir.channelyar.telegrambot D/OkHttp: --> END POST (195-byte body)
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: <-- 400 Bad Request https://api.telegram.org/bot373381534:AAEtYPzduCbY05LAUWP0uEobg1TYyAb5ibA/sendMessage (180ms)
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Server: nginx/1.10.0
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Date: Sun, 26 Mar 2017 14:19:51 GMT
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Content-Type: application/json
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Content-Length: 83
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Connection: keep-alive
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Access-Control-Allow-Origin: *
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: {"ok":false,"error_code":400,"description":"Bad Request: inline keyboard expected"}
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot D/OkHttp: <-- END HTTP (83-byte body)
03-26 18:49:54.782 19741-19741/ir.channelyar.telegrambot E/TRT: false
03-26 18:49:54.782 19741-21183/ir.channelyar.telegrambot D/OkHttp: --> POST https://api.telegram.org/bot373381534:AAEtYPzduCbY05LAUWP0uEobg1TYyAb5ibA/sendMessage http/1.1
03-26 18:49:54.782 19741-21183/ir.channelyar.telegrambot D/OkHttp: Content-Type: application/x-www-form-urlencoded
03-26 18:49:54.782 19741-21183/ir.channelyar.telegrambot D/OkHttp: Content-Length: 195
03-26 18:49:54.782 19741-21183/ir.channelyar.telegrambot D/OkHttp: reply_to_message_id=1&text=Test&parse_mode=HTML&reply_markup=%7B%22force_reply%22%3Atrue%2C%22selective%22%3Afalse%7D&disable_web_page_preview=true&chat_id=%40textion_me&disable_notification=true
03-26 18:49:54.782 19741-21183/ir.channelyar.telegrambot D/OkHttp: --> END POST (195-byte body)
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: <-- 400 Bad Request https://api.telegram.org/bot373381534:AAEtYPzduCbY05LAUWP0uEobg1TYyAb5ibA/sendMessage (159ms)
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Server: nginx/1.10.0
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Date: Sun, 26 Mar 2017 14:19:52 GMT
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Content-Type: application/json
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Content-Length: 83
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Connection: keep-alive
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Access-Control-Allow-Origin: *
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: {"ok":false,"error_code":400,"description":"Bad Request: inline keyboard expected"}
03-26 18:49:54.942 19741-21183/ir.channelyar.telegrambot D/OkHttp: <-- END HTTP (83-byte body)
`

**Comment by shahinesi** [comment]
When I delete the following code works correctly.
`                            .parseMode(ParseMode.HTML)
                            .disableWebPagePreview(true)
                            .disableNotification(true)
                            .replyToMessageId(1)
                            .replyMarkup(new ForceReply());`
But the problem anymore! Each time the code is executed twice to send the message!
