### ISSUE TITLE
sendPhoto

### ISSUE THREAD

**Issue by capitann** [pengrad/java-telegram-bot-api#76]
Hello. 
Is it correct use sendPhoto like next example?
SendResponse send = bot.execute(new SendPhoto(telegram_chat_id, data?.image).caption("caption"))
Message message = send.message()

Where data?.image is a byte from image, encoded in base64 string.
In logger send is null. Where I have problem?
Thanks for answer!

**Comment by capitann** [comment]
Sorry, may be I should send like String file_id or Url, undestood my mistake.

**Comment by pengrad** [comment]
Yes, Base64 is not supported as i know. 
https://core.telegram.org/bots/api#sending-files
You can send as File or byte[] from file
