### ISSUE TITLE
Twice per post!

### ISSUE THREAD

**Issue by shahinesi** [pengrad/java-telegram-bot-api#78]
the problem anymore! Each time the code is executed twice to send the message!
me Code
`SendMessage request = new SendMessage(chatId,"Test");
                    // sync
                    SendResponse sendResponse = bot.execute(request);
                    boolean ok = sendResponse.isOk();
                    Log.e("SendMessage",ok +"");
                    // async
                    bot.execute(request);
                    if (ok) {
                        Log.e("SendPhoto", "ارسال شد");
                    }
                    else {
                        Log.e("SendPhoto","ارسال نشد");
                    }`

**Comment by pengrad** [comment]
Because u call `bot.execute` twice
