### ISSUE TITLE
Help With Example

### ISSUE THREAD

**Issue by gotoabhi** [pengrad/java-telegram-bot-api#8]
Thanks a lot for publishing code and good explanation. Can you post some examples, complete code as well to understand more.

**Comment by pengrad** [comment]
Hi, I am thinking about creation bootstrap-template to start using telegram bots on Openshift platform.
Will try to post it in few days.

**Comment by gotoabhi** [comment]
Thanks for replying.

Actually I was looking on many solutions and found your one to much cleaner and easy to understand. There are many solutions but for java your one is the best.

See if you can spend some time to write java classes that explain about the examples you have.
From: Stanislav Parshin
Sent: Tuesday, 8 December 2015 17:05
To: pengrad/java-telegram-bot-api
Reply To: pengrad/java-telegram-bot-api
Cc: Abhishek
Subject: Re: [java-telegram-bot-api] Help With Example (#8)


Hi, I am thinking about creation bootstrap-template to start using telegram bots on Openshift platform.
Will try to post it in few days.

---

**Comment by pengrad** [comment]
Take a look here.
https://github.com/pengrad/java-telegram-openshift
It's a template to deploy telegram bots built by with this library on OpenShift
