### ISSUE TITLE
Bad Request: inline keyboard expected

### ISSUE THREAD

**Issue by drsaaron** [pengrad/java-telegram-bot-api#82]
I'm testing a simple program to send a message and follow your code samples.  The program is

`
        TelegramBot bot = TelegramBotAdapter.build(TOKEN);

        String message = "this is from java.";

        SendMessage request = new SendMessage(CHANNEL, message)
                .parseMode(ParseMode.HTML)
                .disableWebPagePreview(true)
                .disableNotification(true)
                .replyToMessageId(1)
                .replyMarkup(new ForceReply());

        SendResponse sendResponse = bot.execute(request);
        boolean ok = sendResponse.isOk();
        if (!ok) {
            System.err.println("error sending message");
            System.err.println(sendResponse.description());
        }
        Message response = sendResponse.message();
        System.out.println("response: " + sendResponse.toString());`

And it fails with the message 

> error sending message
Bad Request: inline keyboard expected
response: SendResponse{result=null}

**Comment by pengrad** [comment]
I think you're trying to reply to message which is actually InlineMessage. 
That's why API asks you to specify inline keyboard.
Try to change `.replyToMessageId(1)` with other messageId.

**Comment by pengrad** [comment]
Helped?

**Comment by drsaaron** [comment]
Sorry, yes.  All good now.  I wasn't replying to anything, so I took those parts out and it works like a charm.  Thanks.
On Sunday, April 16, 2017, 9:09:11 PM CDT, Stanislav Parshin <notifications@github.com> wrote:
Helped?
