### ISSUE TITLE
Echo Photo

### ISSUE THREAD

**Issue by DenisWpk** [pengrad/java-telegram-bot-api#85]
Hi! 

I need your help. May be i do something wrong...
I want to get file from user and send it back.
My code:
 <code>PhotoSize[] p = message.photo();
Integer fileSize = 0;
String url = "";
for (PhotoSize sss : p) {
   GetFile request = new GetFile(sss.fileId());
   GetFileResponse getFileResponse = bot.execute(request);

   File file = getFileResponse.file(); // com.pengrad.telegrambot.model.File
   if (file.fileSize() > fileSize) {
   fileSize = file.fileSize();
		url = bot.getFullFilePath(file);
   }
}
sendPhoto(message, replyMarkup, url)

private void sendPhoto(Message message, Keyboard replyMarkup, String url) {
if (replyMarkup == null) {
	Keyboard replyKeyboardHide = new ReplyKeyboardRemove();
	replyMarkup = replyKeyboardHide;
}

SendPhoto request = new SendPhoto(message.from().id(), url).disableNotification(true).replyMarkup(replyMarkup);
bot.execute(request);
};</code>

I try this code with another url (from Google Drive) and it worked. 
I send this url: https://api.telegram.org/file/bot310311688:AAF5T353YIk-L1CCQRkg5ZF41iGpoTlRnag/photos/file_16.jpg

Thank for your help!

**Comment by pengrad** [comment]
I don't understand you

**Comment by DenisWpk** [comment]
I send photo to bot like a user. In server part i receive photo, get download url and send photo to user back by url. And user doesn't get this photo. I don't understand why

**Comment by pengrad** [comment]
Can you post code normally?

**Comment by DenisWpk** [comment]
```java
PhotoSize[] p = message.photo();
Integer fileSize = 0;
String url = "";
for (PhotoSize sss: p) {
 GetFile request = new GetFile(sss.fileId());
 GetFileResponse getFileResponse = bot.execute(request);

 File file = getFileResponse.file(); // com.pengrad.telegrambot.model.File
 if (file.fileSize() > fileSize) {
  fileSize = file.fileSize();
  url = bot.getFullFilePath(file);
 }
}

sendPhoto(message, replyMarkup, url);

private void sendPhoto(Message message, Keyboard replyMarkup, String url) {
 if (replyMarkup == null) {
  Keyboard replyKeyboardHide = new ReplyKeyboardRemove();
  replyMarkup = replyKeyboardHide;
 }
 System.out.println("message.from().id() " + message.from().id());
 SendPhoto request = new SendPhoto(message.from().id(), url).disableNotification(true).replyMarkup(replyMarkup);
 bot.execute(request);
}
```

**Comment by pengrad** [comment]
Try to use debug mode and check response from telegram api
