### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by kiberzoid** [pengrad/java-telegram-bot-api#87]
Hi!
When I set webhook (using async variant), where should I handle incoming messages? In onResponse(SetWebhook request, BaseResponse response) method?

**Comment by pengrad** [comment]
Incoming messages will be sent to url you specified in SetWebhook method.

You can parse them later with:
```java
Update update = BotUtils.parseUpdate(stringRequest); // from String
Update update = BotUtils.parseUpdate(reader); // or from java.io.Reader

Message message = update.message();
```
