### ISSUE TITLE
bot.getFullFilePath(file) does not escape spaces

### ISSUE THREAD

**Issue by hdghg** [pengrad/java-telegram-bot-api#90]
Sorry for my poor English.
I'm getting rare errror on following condition:

    String fullFilePath = bot.getFullFilePath(file);
    HttpGet get = new HttpGet(fullFilePath);
    CloseableHttpResponse execute = HttpClientBuilder.create().build().execute(get)
    HttpEntity entity = execute.getEntity();
    byte[] content = IOUtils.toByteArray(entity.getContent());

This code produces following error:

    Illegal character in path at index 97: https://api.telegram.org/file/bot<my_token>/animations/sTgtJHB (1).mp4

I fixed it by replacing first line with `String fullFilePath = bot.getFullFilePath(file).replace(" ", "%20");` but I still unsure whose issue it is - mine or library's?

**Comment by pengrad** [comment]
I think library's.
Thanks for mentioning, will fix it to return encoded url.

**Comment by pengrad** [comment]
Fixed in 3.0.1
