### ISSUE TITLE
Payments Test. Yandex.Money

### ISSUE THREAD

**Issue by DenisWpk** [pengrad/java-telegram-bot-api#93]
Hi!

I try test payments and used Yandex.Money as provider. I create test token via BotFather.
I call sendinvoice method and don't get invoice message from telegram and any errors. 
I tried to use debug mode but didn't get a result. 
Below my code:
```java
bot = TelegramBotAdapter.build(token);
bot.setUpdatesListener(new UpdatesListener() {
 @Override
 public int process(List < Update > updates) {
  if (updates.size() > 0) {
   for (Update update: updates) {
    if (update.message() != null) {
     SendInvoice sendInvoice = new SendInvoice(update.message().from().id(), "title", "desc", "my_payload", "38176####:TEST:###", "start_parameter", "USD", new LabeledPrice("label", 200));
     bot.execute(sendInvoice);
    }
   }
  }

  return UpdatesListener.CONFIRMED_UPDATES_ALL;
 }
});
```
Thank you for response.

**Comment by pengrad** [comment]
And?
If SendInvoice was success, how do you want me to help you?
Invoice message should come to user's telegram app, not your bot

**Comment by DenisWpk** [comment]
I send invoice message not my bot but to user on any message from him. 
```java
SendInvoice sendInvoice = new SendInvoice(update.message().from().id()
```

**Comment by DenisWpk** [comment]
I find my error. 
My price was below of minimum.
https://core.telegram.org/bots/payments/currencies.json
