### ISSUE TITLE
Payments API

### ISSUE THREAD

**Issue by DenisWpk** [pengrad/java-telegram-bot-api#94]
Hi, Stanislav!

Thank you for your library! 

Do you plan add optional fields in sendInvoice?
https://core.telegram.org/bots/api#sendinvoice

**Comment by pengrad** [comment]
What fields do you want there?

**Comment by DenisWpk** [comment]
About photo: 
photo_url, photo_size, photo_width, photo_height.

**Comment by pengrad** [comment]
Did you ever try to open SendInvoice?
All this methods are already there.
Please be more professional
