### ISSUE TITLE
Payments Photo

### ISSUE THREAD

**Issue by DenisWpk** [pengrad/java-telegram-bot-api#95]
Hi!
I know, that I bored you yet(
I try to send image in payment and its not displayed.
I try to use directlink from gdrive (https://drive.google.com/uc?export=download&id=0BydBkApd9R5PQWdlQTcwWDh4SjA), 1fichier (https://1fichier.com/?8g8aoeaefa). Load image in bot and pass fullpath of file in telegram as url.
I try to add and remove photosize, width, height in sendinvoice. 
I try to use big and small images. 
I try to use debug mode and search answer in google but no result. 
Below my code and result: 
```java 
SendInvoice sendInvoice = new SendInvoice(update.message().from().id(), "Мяч футбольный",
  "Превосходный футбольный мяч для активного отдыха", "my_payload", "381######:TEST:###", "my_start_param", "RUB",
  new LabeledPrice("Цена", 10000)).photoUrl("https://1fichier.com/?8g8aoeaefa")
 .replyMarkup(new InlineKeyboardMarkup(
  new InlineKeyboardButton[] {
   new InlineKeyboardButton("Купить 100 руб.").pay()
  }));
SendResponse response = bot.execute(sendInvoice);
```
![1e8c25d4-febc-41d8-890f-03199d7ab1f1](https://user-images.githubusercontent.com/8546089/27224371-4244a35a-52ae-11e7-9394-3257bc80312c.jpg)

I don't understand where is my error( 
Thanks for any suggestions.

**Comment by pengrad** [comment]
I don't know. 
Test telegram api directly -ask question on SO
