### ISSUE TITLE
forwardMessage

### ISSUE THREAD

**Issue by mehran75** [pengrad/java-telegram-bot-api#97]
how should I send forwarded message??

i tried this but throw error
 `new ForwardMessage(
                        message.contact().userId()
                        , update.message().forwardFromChat().username()
                        , message.forwardFromMessageId());
`

**Comment by pengrad** [comment]
What error?

**Comment by mehran75** [comment]
I don't know it does not show me error:|
it just do loop over and over..
this is my code

bot.setUpdatesListener(new UpdatesListener() {
            @Override
            public int process(List<Update> list) {

                Update update = list.get(0);

                Message message = update.message();


                message.text();

                new ForwardMessage(
                        message.contact().userId()
                        , update.message().forwardFromChat().username()
                        , message.forwardFromMessageId());
                return update.updateId();
            }
        });

**Comment by mehran75** [comment]
my problem was this `message.contact().userId()`

it's ok now i solve it, but the message not send to user:|

**Comment by mehran75** [comment]
solve it too:)

` update.message().forwardFromChat().username()` change this like this 
` "@" + update.message().forwardFromChat().username()`
