### ISSUE TITLE
GetUpdates.allowedUpdates(String) method's param syntax

### ISSUE THREAD

**Issue by theskylineguy** [pengrad/java-telegram-bot-api#99]
Hello @pengrad!

How am I supposed to enter the params in the method above in case I want to allow getting more than one type of updates (but not all of them)?
Since https://core.telegram.org/bots/api#getupdates states _allowed_updates_ to be an array of String and your framework only gives String for that parameter?

Thanks in advance.
@theskylineguy

**Comment by pengrad** [comment]
My "framework" takes array as param

**Comment by theskylineguy** [comment]
Sorry, ore more thing: do I have to enter **snake_case** Strings or **camelCase** Strings?

@theskylineguy
